/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { Inject, Injectable } from '@nestjs/common';
import * as v from 'valibot';
import * as mi from '@/misc/schema/index.js';
import { Endpoint } from '@/server/api/endpoint-base.js';
import { MetaService } from '@/core/MetaService.js';
import type { Config } from '@/config.js';
import { DI } from '@/di-symbols.js';
import { DEFAULT_POLICIES } from '@/core/RoleService.js';
import { SystemAccountService } from '@/core/SystemAccountService.js';
import { packedMetaClientOptionsSchema } from '@/models/schema/meta.js';

export const meta = {
	tags: ['meta'],

	requireCredential: true,
	requireAdmin: true,
	kind: 'read:admin:meta',

	res: v.object({
		cacheRemoteFiles: v.boolean(),
		cacheRemoteSensitiveFiles: v.boolean(),
		emailRequiredForSignup: v.boolean(),
		enableHcaptcha: v.boolean(),
		hcaptchaSiteKey: v.nullable(v.string()),
		enableMcaptcha: v.boolean(),
		mcaptchaSiteKey: v.nullable(v.string()),
		mcaptchaInstanceUrl: v.nullable(v.string()),
		enableRecaptcha: v.boolean(),
		recaptchaSiteKey: v.nullable(v.string()),
		enableTurnstile: v.boolean(),
		turnstileSiteKey: v.nullable(v.string()),
		enableTestcaptcha: v.boolean(),
		googleAnalyticsMeasurementId: v.nullable(v.string()),
		swPublickey: v.nullable(v.string()),
		mascotImageUrl: v.pipe(v.nullable(v.string()), mi.openApi({ default: '/assets/ai.png' })),
		bannerUrl: v.nullable(v.string()),
		serverErrorImageUrl: v.nullable(v.string()),
		infoImageUrl: v.nullable(v.string()),
		notFoundImageUrl: v.nullable(v.string()),
		iconUrl: v.nullable(v.string()),
		app192IconUrl: v.nullable(v.string()),
		app512IconUrl: v.nullable(v.string()),
		enableEmail: v.boolean(),
		enableServiceWorker: v.boolean(),
		translatorAvailable: v.boolean(),
		silencedHosts: v.optional(v.array(v.string())),
		mediaSilencedHosts: v.array(v.string()),
		pinnedUsers: v.array(v.string()),
		hiddenTags: v.array(v.string()),
		blockedHosts: v.array(v.string()),
		sensitiveWords: v.array(v.string()),
		prohibitedWords: v.array(v.string()),
		prohibitedWordsForNameOfUser: v.array(v.string()),
		bannedEmailDomains: v.optional(v.array(v.string())),
		preservedUsernames: v.array(v.string()),
		hcaptchaSecretKey: v.nullable(v.string()),
		mcaptchaSecretKey: v.nullable(v.string()),
		recaptchaSecretKey: v.nullable(v.string()),
		turnstileSecretKey: v.nullable(v.string()),
		sensitiveMediaDetection: v.picklist(['none', 'all', 'local', 'remote']),
		sensitiveMediaDetectionSensitivity: v.picklist(['medium', 'low', 'high', 'veryLow', 'veryHigh']),
		setSensitiveFlagAutomatically: v.boolean(),
		enableSensitiveMediaDetectionForVideos: v.boolean(),
		sensitiveMediaDetectionApiUrl: v.nullable(v.string()),
		sensitiveMediaDetectionApiKey: v.nullable(v.string()),
		sensitiveMediaDetectionTimeout: v.number(),
		sensitiveMediaDetectionMaxImagesPerRequest: v.number(),
		proxyAccountId: mi.idString(),
		email: v.nullable(v.string()),
		smtpSecure: v.boolean(),
		smtpHost: v.nullable(v.string()),
		smtpPort: v.nullable(v.number()),
		smtpUser: v.nullable(v.string()),
		smtpPass: v.nullable(v.string()),
		swPrivateKey: v.nullable(v.string()),
		useObjectStorage: v.boolean(),
		objectStorageBaseUrl: v.nullable(v.string()),
		objectStorageBucket: v.nullable(v.string()),
		objectStoragePrefix: v.nullable(v.string()),
		objectStorageEndpoint: v.nullable(v.string()),
		objectStorageRegion: v.nullable(v.string()),
		objectStoragePort: v.nullable(v.number()),
		objectStorageAccessKey: v.nullable(v.string()),
		objectStorageSecretKey: v.nullable(v.string()),
		objectStorageUseSSL: v.boolean(),
		objectStorageUseProxy: v.boolean(),
		objectStorageSetPublicRead: v.boolean(),
		enableIpLogging: v.boolean(),
		enableActiveEmailValidation: v.boolean(),
		enableVerifymailApi: v.boolean(),
		verifymailAuthKey: v.nullable(v.string()),
		enableTruemailApi: v.boolean(),
		truemailInstance: v.nullable(v.string()),
		truemailAuthKey: v.nullable(v.string()),
		enableChartsForRemoteUser: v.boolean(),
		enableChartsForFederatedInstances: v.boolean(),
		enableStatsForFederatedInstances: v.boolean(),
		enableServerMachineStats: v.boolean(),
		enableIdenticonGeneration: v.boolean(),
		manifestJsonOverride: v.string(),
		// json-schema 側も properties 無しの object で無検証だったため mi.anyObject() を維持 (cookbook R1)
		policies: mi.anyObject(),
		enableFanoutTimeline: v.boolean(),
		enableFanoutTimelineDbFallback: v.boolean(),
		perLocalUserUserTimelineCacheMax: v.number(),
		perRemoteUserUserTimelineCacheMax: v.number(),
		perUserHomeTimelineCacheMax: v.number(),
		perUserListTimelineCacheMax: v.number(),
		enableReactionsBuffering: v.boolean(),
		notesPerOneAd: v.number(),
		backgroundImageUrl: v.nullable(v.string()),
		deeplAuthKey: v.nullable(v.string()),
		deeplIsPro: v.boolean(),
		defaultDarkTheme: v.nullable(v.string()),
		defaultLightTheme: v.nullable(v.string()),
		clientOptions: packedMetaClientOptionsSchema,
		description: v.nullable(v.string()),
		disableRegistration: v.boolean(),
		impressumUrl: v.nullable(v.string()),
		maintainerEmail: v.nullable(v.string()),
		maintainerName: v.nullable(v.string()),
		name: v.nullable(v.string()),
		shortName: v.nullable(v.string()),
		objectStorageS3ForcePathStyle: v.boolean(),
		privacyPolicyUrl: v.nullable(v.string()),
		inquiryUrl: v.nullable(v.string()),
		repositoryUrl: v.nullable(v.string()),
		feedbackUrl: v.nullable(v.string()),
		summalyProxy: v.pipe(
			v.nullable(v.string()),
			mi.deprecated(),
			v.description('[Deprecated] Use "urlPreviewSummaryProxyUrl" instead.'),
		),
		themeColor: v.nullable(v.string()),
		tosUrl: v.nullable(v.string()),
		uri: v.string(),
		version: v.string(),
		urlPreviewEnabled: v.boolean(),
		urlPreviewAllowRedirect: v.boolean(),
		urlPreviewTimeout: v.number(),
		urlPreviewMaximumContentLength: v.number(),
		urlPreviewRequireContentLength: v.boolean(),
		urlPreviewUserAgent: v.nullable(v.string()),
		urlPreviewSummaryProxyUrl: v.nullable(v.string()),
		urlPreviewSensitiveList: v.array(v.string()),
		federation: v.picklist(['all', 'specified', 'none']),
		federationHosts: v.array(v.string()),
		deliverSuspendedSoftware: v.array(v.object({
			software: v.string(),
			versionRange: v.string(),
		})),
		singleUserMode: v.boolean(),
		ugcVisibilityForVisitor: v.picklist(['all', 'local', 'none']),
		proxyRemoteFiles: v.boolean(),
		signToActivityPubGet: v.boolean(),
		allowExternalApRedirect: v.boolean(),
		enableRemoteNotesCleaning: v.boolean(),
		remoteNotesCleaningExpiryDaysForEachNotes: v.number(),
		remoteNotesCleaningMaxProcessingDurationInMinutes: v.number(),
		showRoleBadgesOfRemoteUsers: v.boolean(),
	}),
} as const;

export const paramDef = v.object({});

@Injectable()
export default class extends Endpoint<typeof meta, typeof paramDef> { // eslint-disable-line import/no-default-export
	constructor(
		@Inject(DI.config)
		private config: Config,

		private metaService: MetaService,
		private systemAccountService: SystemAccountService,
	) {
		super(meta, paramDef, async () => {
			const instance = await this.metaService.fetch(true);

			const proxy = await this.systemAccountService.fetch('proxy');

			return {
				maintainerName: instance.maintainerName,
				maintainerEmail: instance.maintainerEmail,
				version: this.config.version,
				name: instance.name,
				shortName: instance.shortName,
				uri: this.config.url,
				description: instance.description,
				langs: instance.langs,
				tosUrl: instance.termsOfServiceUrl,
				repositoryUrl: instance.repositoryUrl,
				feedbackUrl: instance.feedbackUrl,
				impressumUrl: instance.impressumUrl,
				privacyPolicyUrl: instance.privacyPolicyUrl,
				inquiryUrl: instance.inquiryUrl,
				disableRegistration: instance.disableRegistration,
				emailRequiredForSignup: instance.emailRequiredForSignup,
				enableHcaptcha: instance.enableHcaptcha,
				hcaptchaSiteKey: instance.hcaptchaSiteKey,
				enableMcaptcha: instance.enableMcaptcha,
				mcaptchaSiteKey: instance.mcaptchaSitekey,
				mcaptchaInstanceUrl: instance.mcaptchaInstanceUrl,
				enableRecaptcha: instance.enableRecaptcha,
				recaptchaSiteKey: instance.recaptchaSiteKey,
				enableTurnstile: instance.enableTurnstile,
				turnstileSiteKey: instance.turnstileSiteKey,
				enableTestcaptcha: instance.enableTestcaptcha,
				googleAnalyticsMeasurementId: instance.googleAnalyticsMeasurementId,
				swPublickey: instance.swPublicKey,
				themeColor: instance.themeColor,
				mascotImageUrl: instance.mascotImageUrl,
				bannerUrl: instance.bannerUrl,
				serverErrorImageUrl: instance.serverErrorImageUrl,
				notFoundImageUrl: instance.notFoundImageUrl,
				infoImageUrl: instance.infoImageUrl,
				iconUrl: instance.iconUrl,
				app192IconUrl: instance.app192IconUrl,
				app512IconUrl: instance.app512IconUrl,
				backgroundImageUrl: instance.backgroundImageUrl,
				logoImageUrl: instance.logoImageUrl,
				defaultLightTheme: instance.defaultLightTheme,
				defaultDarkTheme: instance.defaultDarkTheme,
				clientOptions: instance.clientOptions,
				enableEmail: instance.enableEmail,
				enableServiceWorker: instance.enableServiceWorker,
				translatorAvailable: instance.deeplAuthKey != null,
				cacheRemoteFiles: instance.cacheRemoteFiles,
				cacheRemoteSensitiveFiles: instance.cacheRemoteSensitiveFiles,
				pinnedUsers: instance.pinnedUsers,
				hiddenTags: instance.hiddenTags,
				blockedHosts: instance.blockedHosts,
				silencedHosts: instance.silencedHosts,
				mediaSilencedHosts: instance.mediaSilencedHosts,
				sensitiveWords: instance.sensitiveWords,
				prohibitedWords: instance.prohibitedWords,
				prohibitedWordsForNameOfUser: instance.prohibitedWordsForNameOfUser,
				preservedUsernames: instance.preservedUsernames,
				hcaptchaSecretKey: instance.hcaptchaSecretKey,
				mcaptchaSecretKey: instance.mcaptchaSecretKey,
				recaptchaSecretKey: instance.recaptchaSecretKey,
				turnstileSecretKey: instance.turnstileSecretKey,
				sensitiveMediaDetection: instance.sensitiveMediaDetection,
				sensitiveMediaDetectionSensitivity: instance.sensitiveMediaDetectionSensitivity,
				setSensitiveFlagAutomatically: instance.setSensitiveFlagAutomatically,
				enableSensitiveMediaDetectionForVideos: instance.enableSensitiveMediaDetectionForVideos,
				sensitiveMediaDetectionApiUrl: instance.sensitiveMediaDetectionApiUrl,
				sensitiveMediaDetectionApiKey: instance.sensitiveMediaDetectionApiKey,
				sensitiveMediaDetectionTimeout: instance.sensitiveMediaDetectionTimeout,
				sensitiveMediaDetectionMaxImagesPerRequest: instance.sensitiveMediaDetectionMaxImagesPerRequest,
				proxyAccountId: proxy.id,
				email: instance.email,
				smtpSecure: instance.smtpSecure,
				smtpHost: instance.smtpHost,
				smtpPort: instance.smtpPort,
				smtpUser: instance.smtpUser,
				smtpPass: instance.smtpPass,
				swPrivateKey: instance.swPrivateKey,
				useObjectStorage: instance.useObjectStorage,
				objectStorageBaseUrl: instance.objectStorageBaseUrl,
				objectStorageBucket: instance.objectStorageBucket,
				objectStoragePrefix: instance.objectStoragePrefix,
				objectStorageEndpoint: instance.objectStorageEndpoint,
				objectStorageRegion: instance.objectStorageRegion,
				objectStoragePort: instance.objectStoragePort,
				objectStorageAccessKey: instance.objectStorageAccessKey,
				objectStorageSecretKey: instance.objectStorageSecretKey,
				objectStorageUseSSL: instance.objectStorageUseSSL,
				objectStorageUseProxy: instance.objectStorageUseProxy,
				objectStorageSetPublicRead: instance.objectStorageSetPublicRead,
				objectStorageS3ForcePathStyle: instance.objectStorageS3ForcePathStyle,
				deeplAuthKey: instance.deeplAuthKey,
				deeplIsPro: instance.deeplIsPro,
				enableIpLogging: instance.enableIpLogging,
				enableActiveEmailValidation: instance.enableActiveEmailValidation,
				enableVerifymailApi: instance.enableVerifymailApi,
				verifymailAuthKey: instance.verifymailAuthKey,
				enableTruemailApi: instance.enableTruemailApi,
				truemailInstance: instance.truemailInstance,
				truemailAuthKey: instance.truemailAuthKey,
				enableChartsForRemoteUser: instance.enableChartsForRemoteUser,
				enableChartsForFederatedInstances: instance.enableChartsForFederatedInstances,
				enableStatsForFederatedInstances: instance.enableStatsForFederatedInstances,
				enableServerMachineStats: instance.enableServerMachineStats,
				enableIdenticonGeneration: instance.enableIdenticonGeneration,
				bannedEmailDomains: instance.bannedEmailDomains,
				policies: { ...DEFAULT_POLICIES, ...instance.policies },
				manifestJsonOverride: instance.manifestJsonOverride,
				enableFanoutTimeline: instance.enableFanoutTimeline,
				enableFanoutTimelineDbFallback: instance.enableFanoutTimelineDbFallback,
				perLocalUserUserTimelineCacheMax: instance.perLocalUserUserTimelineCacheMax,
				perRemoteUserUserTimelineCacheMax: instance.perRemoteUserUserTimelineCacheMax,
				perUserHomeTimelineCacheMax: instance.perUserHomeTimelineCacheMax,
				perUserListTimelineCacheMax: instance.perUserListTimelineCacheMax,
				enableReactionsBuffering: instance.enableReactionsBuffering,
				notesPerOneAd: instance.notesPerOneAd,
				summalyProxy: instance.urlPreviewSummaryProxyUrl,
				urlPreviewEnabled: instance.urlPreviewEnabled,
				urlPreviewAllowRedirect: instance.urlPreviewAllowRedirect,
				urlPreviewTimeout: instance.urlPreviewTimeout,
				urlPreviewMaximumContentLength: instance.urlPreviewMaximumContentLength,
				urlPreviewRequireContentLength: instance.urlPreviewRequireContentLength,
				urlPreviewUserAgent: instance.urlPreviewUserAgent,
				urlPreviewSummaryProxyUrl: instance.urlPreviewSummaryProxyUrl,
				urlPreviewSensitiveList: instance.urlPreviewSensitiveList,
				federation: instance.federation,
				federationHosts: instance.federationHosts,
				deliverSuspendedSoftware: instance.deliverSuspendedSoftware,
				singleUserMode: instance.singleUserMode,
				ugcVisibilityForVisitor: instance.ugcVisibilityForVisitor,
				proxyRemoteFiles: instance.proxyRemoteFiles,
				signToActivityPubGet: instance.signToActivityPubGet,
				allowExternalApRedirect: instance.allowExternalApRedirect,
				enableRemoteNotesCleaning: instance.enableRemoteNotesCleaning,
				remoteNotesCleaningExpiryDaysForEachNotes: instance.remoteNotesCleaningExpiryDaysForEachNotes,
				remoteNotesCleaningMaxProcessingDurationInMinutes: instance.remoteNotesCleaningMaxProcessingDurationInMinutes,
				showRoleBadgesOfRemoteUsers: instance.showRoleBadgesOfRemoteUsers,
			};
		});
	}
}
