packages:
  - packages/backend
  - packages/frontend-shared
  - packages/frontend
  - packages/frontend-embed
  - packages/sw
  - packages/misskey-js
  - packages/misskey-js/generator
  - packages/misskey-reversi
  - packages/misskey-bubble-game
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@sentry/profiling-node'
  - '@swc/core'
  - '@tensorflow/tfjs-node'
  - bufferutil
  - canvas
  - core-js
  - cypress
  - esbuild
  - msgpackr-extract
  - msw
  - nice-napi
  - re2
  - sharp
  - utf-8-validate
  - v-code-diff
  - vue-demi
ignorePatchFailures: false

catalog:
  "@discordapp/twemoji": "15.1.0"
  "@misskey-dev/summaly": "5.2.1"
  "@rollup/plugin-json": "6.1.0"
  "@rollup/plugin-replace": "6.0.2"
  "@rollup/pluginutils": "5.1.4"
  "@sentry/vue": "9.14.0"
  "@simplewebauthn/types": "12.0.0"
  "@swc/jest": "0.2.38"
  "@tabler/icons-webfont": "3.31.0"
  "@testing-library/vue": "8.1.0"
  "@twemoji/parser": "15.1.1"
  "@types/estree": "1.0.7"
  "@types/jest": "29.5.14"
  "@types/matter-js": "0.19.8"
  "@types/micromatch": "4.0.9"
  "@types/node": "22.15.2"
  "@types/punycode.js": "npm:@types/punycode@2.1.4"
  "@types/sanitize-html": "2.15.0"
  "@types/seedrandom": "3.0.8"
  "@types/tinycolor2": "1.4.6"
  "@types/ws": "8.18.1"
  "@typescript-eslint/eslint-plugin": "8.31.0"
  "@typescript-eslint/parser": "8.31.0"
  "@typescript/lib-webworker": "npm:@types/serviceworker@0.0.74"
  "@vitejs/plugin-vue": "5.2.3"
  "@vitest/coverage-v8": "3.1.2"
  "@vue/compiler-sfc": "3.5.13"
  "@vue/runtime-core": "3.5.13"
  "acorn": "8.14.1"
  "astring": "1.9.0"
  "buraha": "0.0.1"
  "cross-env": "7.0.3"
  "esbuild": "0.25.3"
  "eslint-plugin-import": "2.31.0"
  "eslint-plugin-vue": "10.0.0"
  "estree-walker": "3.0.3"
  "eventemitter3": "5.0.1"
  "execa": "9.5.2"
  "fast-glob": "3.3.3"
  "glob": "11.0.2"
  "idb-keyval": "6.2.1"
  "intersection-observer": "0.12.2"
  "jest": "29.7.0"
  "json5": "2.2.3"
  "matter-js": "0.20.0"
  "mfm-js": "0.24.0"
  "micromatch": "4.0.8"
  "msw": "2.7.5"
  "ncp": "2.0.0"
  "nodemon": "3.1.10"
  "prettier": "3.5.3"
  "punycode.js": "2.3.1"
  "rollup": "4.40.0"
  "sanitize-html": "2.16.0"
  "sass": "1.87.0"
  "seedrandom": "3.0.5"
  "shiki": "3.3.0"
  "start-server-and-test": "2.0.11"
  "strict-event-emitter-types": "2.0.0"
  "tinycolor2": "1.6.0"
  "tsc-alias": "1.8.15"
  "tsconfig-paths": "4.2.0"
  "typescript": "5.8.3"
  "uuid": "11.1.0"
  "vite": "6.3.4"
  "vite-plugin-turbosnap": "1.0.3"
  "vue": "3.5.13"
  "vue-component-type-helpers": "2.2.10"
  "vue-eslint-parser": "10.1.3"
  "vue-tsc": "2.2.10"

catalogs:
  "happy-dom16":
    "happy-dom": "16.8.1"
  "happy-dom17":
    "happy-dom": "17.4.4"
  "date-fns2":
    "date-fns": "2.30.0"
  "date-fns4":
    "date-fns": "4.1.0"
