packages:
 - 'packages/backend'
 - 'packages/frontend-shared'
 - 'packages/frontend'
 - 'packages/frontend-embed'
 - 'packages/sw'
 - 'packages/misskey-js'
 - 'packages/misskey-js/generator'
 - 'packages/misskey-reversi'
 - 'packages/misskey-bubble-game'
