import { } from 'typeorm';
import { db } from '@/db/postgre.js';

import { Announcement } from './entities/announcement.js';
import { AnnouncementRead } from './entities/announcement-read.js';
import { Instance } from './entities/instance.js';
import { Poll } from './entities/poll.js';
import { PollVote } from './entities/poll-vote.js';
import { Meta } from './entities/meta.js';
import { SwSubscription } from './entities/sw-subscription.js';
import { NoteThreadMuting } from './entities/note-thread-muting.js';
import { NoteUnread } from './entities/note-unread.js';
import { RegistrationTicket } from './entities/registration-tickets.js';
import { User } from './entities/user.js';
import { Note } from './entities/note.js';
import { DriveFile } from './entities/drive-file.js';
import { DriveFolder } from './entities/drive-folder.js';
import { AccessToken } from './entities/access-token.js';
import { UserNotePining } from './entities/user-note-pining.js';
import { Signin } from './entities/signin.js';
import { MessagingMessage } from './entities/messaging-message.js';
import { UserList } from './entities/user-list.js';
import { UserListJoining } from './entities/user-list-joining.js';
import { UserGroup } from './entities/user-group.js';
import { UserGroupJoining } from './entities/user-group-joining.js';
import { UserGroupInvitation } from './entities/user-group-invitation.js';
import { FollowRequest } from './entities/follow-request.js';
import { Muting } from './entities/muting.js';
import { Blocking } from './entities/blocking.js';
import { NoteReaction } from './entities/note-reaction.js';
import { Notification } from './entities/notification.js';
import { NoteFavorite } from './entities/note-favorite.js';
import { UserPublickey } from './entities/user-publickey.js';
import { UserKeypair } from './entities/user-keypair.js';
import { App } from './entities/app.js';
import { Following } from './entities/following.js';
import { AbuseUserReport } from './entities/abuse-user-report.js';
import { AuthSession } from './entities/auth-session.js';
import { UserProfile } from './entities/user-profile.js';
import { AttestationChallenge } from './entities/attestation-challenge.js';
import { UserSecurityKey } from './entities/user-security-key.js';
import { Hashtag } from './entities/hashtag.js';
import { Page } from './entities/page.js';
import { PageLike } from './entities/page-like.js';
import { GalleryPost } from './entities/gallery-post.js';
import { GalleryLike } from './entities/gallery-like.js';
import { ModerationLog } from './entities/moderation-log.js';
import { UsedUsername } from './entities/used-username.js';
import { Clip } from './entities/clip.js';
import { ClipNote } from './entities/clip-note.js';
import { Antenna } from './entities/antenna.js';
import { AntennaNote } from './entities/antenna-note.js';
import { PromoNote } from './entities/promo-note.js';
import { PromoRead } from './entities/promo-read.js';
import { Emoji } from './entities/emoji.js';
import { Relay } from './entities/relay.js';
import { Channel } from './entities/channel.js';
import { MutedNote } from './entities/muted-note.js';
import { ChannelFollowing } from './entities/channel-following.js';
import { ChannelNotePining } from './entities/channel-note-pining.js';
import { RegistryItem } from './entities/registry-item.js';
import { Ad } from './entities/ad.js';
import { PasswordResetRequest } from './entities/password-reset-request.js';
import { UserPending } from './entities/user-pending.js';
import { Webhook } from './entities/webhook.js';
import { UserIp } from './entities/user-ip.js';

export const Announcements = db.getRepository(Announcement);
export const AnnouncementReads = db.getRepository(AnnouncementRead);
export const Apps = db.getRepository(App);
export const Notes = db.getRepository(Note);
export const NoteFavorites = db.getRepository(NoteFavorite);
export const NoteThreadMutings = db.getRepository(NoteThreadMuting);
export const NoteReactions = db.getRepository(NoteReaction);
export const NoteUnreads = db.getRepository(NoteUnread);
export const Polls = db.getRepository(Poll);
export const PollVotes = db.getRepository(PollVote);
export const Users = db.getRepository(User);
export const UserProfiles = db.getRepository(UserProfile);
export const UserKeypairs = db.getRepository(UserKeypair);
export const UserPendings = db.getRepository(UserPending);
export const AttestationChallenges = db.getRepository(AttestationChallenge);
export const UserSecurityKeys = db.getRepository(UserSecurityKey);
export const UserPublickeys = db.getRepository(UserPublickey);
export const UserLists = db.getRepository(UserList);
export const UserListJoinings = db.getRepository(UserListJoining);
export const UserGroups = db.getRepository(UserGroup);
export const UserGroupJoinings = db.getRepository(UserGroupJoining);
export const UserGroupInvitations = db.getRepository(UserGroupInvitation);
export const UserNotePinings = db.getRepository(UserNotePining);
export const UserIps = db.getRepository(UserIp);
export const UsedUsernames = db.getRepository(UsedUsername);
export const Followings = db.getRepository(Following);
export const FollowRequests = db.getRepository(FollowRequest);
export const Instances = db.getRepository(Instance);
export const Emojis = db.getRepository(Emoji);
export const DriveFiles = db.getRepository(DriveFile);
export const DriveFolders = db.getRepository(DriveFolder);
export const Notifications = db.getRepository(Notification);
export const Metas = db.getRepository(Meta);
export const Mutings = db.getRepository(Muting);
export const Blockings = db.getRepository(Blocking);
export const SwSubscriptions = db.getRepository(SwSubscription);
export const Hashtags = db.getRepository(Hashtag);
export const AbuseUserReports = db.getRepository(AbuseUserReport);
export const RegistrationTickets = db.getRepository(RegistrationTicket);
export const AuthSessions = db.getRepository(AuthSession);
export const AccessTokens = db.getRepository(AccessToken);
export const Signins = db.getRepository(Signin);
export const MessagingMessages = db.getRepository(MessagingMessage);
export const Pages = db.getRepository(Page);
export const PageLikes = db.getRepository(PageLike);
export const GalleryPosts = db.getRepository(GalleryPost);
export const GalleryLikes = db.getRepository(GalleryLike);
export const ModerationLogs = db.getRepository(ModerationLog);
export const Clips = db.getRepository(Clip);
export const ClipNotes = db.getRepository(ClipNote);
export const Antennas = db.getRepository(Antenna);
export const AntennaNotes = db.getRepository(AntennaNote);
export const PromoNotes = db.getRepository(PromoNote);
export const PromoReads = db.getRepository(PromoRead);
export const Relays = db.getRepository(Relay);
export const MutedNotes = db.getRepository(MutedNote);
export const Channels = db.getRepository(Channel);
export const ChannelFollowings = db.getRepository(ChannelFollowing);
export const ChannelNotePinings = db.getRepository(ChannelNotePining);
export const RegistryItems = db.getRepository(RegistryItem);
export const Webhooks = db.getRepository(Webhook);
export const Ads = db.getRepository(Ad);
export const PasswordResetRequests = db.getRepository(PasswordResetRequest);
