import { Module } from '@nestjs/common';

import { CoreModule } from '@/services/CoreModule.js';
import * as ep___admin_meta from './endpoints/admin/meta.js';
import * as ep___admin_abuseUserReports from './endpoints/admin/abuse-user-reports.js';
import * as ep___admin_accounts_create from './endpoints/admin/accounts/create.js';
import * as ep___admin_accounts_delete from './endpoints/admin/accounts/delete.js';
import * as ep___admin_ad_create from './endpoints/admin/ad/create.js';
import * as ep___admin_ad_delete from './endpoints/admin/ad/delete.js';
import * as ep___admin_ad_list from './endpoints/admin/ad/list.js';
import * as ep___admin_ad_update from './endpoints/admin/ad/update.js';
import * as ep___admin_announcements_create from './endpoints/admin/announcements/create.js';
import * as ep___admin_announcements_delete from './endpoints/admin/announcements/delete.js';
import * as ep___admin_announcements_list from './endpoints/admin/announcements/list.js';
import * as ep___admin_announcements_update from './endpoints/admin/announcements/update.js';
import * as ep___admin_deleteAllFilesOfAUser from './endpoints/admin/delete-all-files-of-a-user.js';
import * as ep___admin_drive_cleanRemoteFiles from './endpoints/admin/drive/clean-remote-files.js';
import * as ep___admin_drive_cleanup from './endpoints/admin/drive/cleanup.js';
import * as ep___admin_drive_files from './endpoints/admin/drive/files.js';
import * as ep___admin_drive_showFile from './endpoints/admin/drive/show-file.js';
import * as ep___admin_emoji_addAliasesBulk from './endpoints/admin/emoji/add-aliases-bulk.js';
import * as ep___admin_emoji_add from './endpoints/admin/emoji/add.js';
import * as ep___admin_emoji_copy from './endpoints/admin/emoji/copy.js';
import * as ep___admin_emoji_deleteBulk from './endpoints/admin/emoji/delete-bulk.js';
import * as ep___admin_emoji_delete from './endpoints/admin/emoji/delete.js';
import * as ep___admin_emoji_importZip from './endpoints/admin/emoji/import-zip.js';
import * as ep___admin_emoji_listRemote from './endpoints/admin/emoji/list-remote.js';
import * as ep___admin_emoji_list from './endpoints/admin/emoji/list.js';
import * as ep___admin_emoji_removeAliasesBulk from './endpoints/admin/emoji/remove-aliases-bulk.js';
import * as ep___admin_emoji_setAliasesBulk from './endpoints/admin/emoji/set-aliases-bulk.js';
import * as ep___admin_emoji_setCategoryBulk from './endpoints/admin/emoji/set-category-bulk.js';
import * as ep___admin_emoji_update from './endpoints/admin/emoji/update.js';
import * as ep___admin_federation_deleteAllFiles from './endpoints/admin/federation/delete-all-files.js';
import * as ep___admin_federation_refreshRemoteInstanceMetadata from './endpoints/admin/federation/refresh-remote-instance-metadata.js';
import * as ep___admin_federation_removeAllFollowing from './endpoints/admin/federation/remove-all-following.js';
import * as ep___admin_federation_updateInstance from './endpoints/admin/federation/update-instance.js';
import * as ep___admin_getIndexStats from './endpoints/admin/get-index-stats.js';
import * as ep___admin_getTableStats from './endpoints/admin/get-table-stats.js';
import * as ep___admin_getUserIps from './endpoints/admin/get-user-ips.js';
import * as ep___admin_invite from './endpoints/admin/invite.js';
import * as ep___admin_moderators_add from './endpoints/admin/moderators/add.js';
import * as ep___admin_moderators_remove from './endpoints/admin/moderators/remove.js';
import * as ep___admin_promo_create from './endpoints/admin/promo/create.js';
import * as ep___admin_queue_clear from './endpoints/admin/queue/clear.js';
import * as ep___admin_queue_deliverDelayed from './endpoints/admin/queue/deliver-delayed.js';
import * as ep___admin_queue_inboxDelayed from './endpoints/admin/queue/inbox-delayed.js';
import * as ep___admin_queue_stats from './endpoints/admin/queue/stats.js';
import * as ep___admin_relays_add from './endpoints/admin/relays/add.js';
import * as ep___admin_relays_list from './endpoints/admin/relays/list.js';
import * as ep___admin_relays_remove from './endpoints/admin/relays/remove.js';
import * as ep___admin_resetPassword from './endpoints/admin/reset-password.js';
import * as ep___admin_resolveAbuseUserReport from './endpoints/admin/resolve-abuse-user-report.js';
import * as ep___admin_sendEmail from './endpoints/admin/send-email.js';
import * as ep___admin_serverInfo from './endpoints/admin/server-info.js';
import * as ep___admin_showModerationLogs from './endpoints/admin/show-moderation-logs.js';
import * as ep___admin_showUser from './endpoints/admin/show-user.js';
import * as ep___admin_showUsers from './endpoints/admin/show-users.js';
import * as ep___admin_silenceUser from './endpoints/admin/silence-user.js';
import * as ep___admin_suspendUser from './endpoints/admin/suspend-user.js';
import * as ep___admin_unsilenceUser from './endpoints/admin/unsilence-user.js';
import * as ep___admin_unsuspendUser from './endpoints/admin/unsuspend-user.js';
import * as ep___admin_updateMeta from './endpoints/admin/update-meta.js';
import * as ep___admin_deleteAccount from './endpoints/admin/delete-account.js';
import * as ep___admin_updateUserNote from './endpoints/admin/update-user-note.js';
import * as ep___announcements from './endpoints/announcements.js';
import * as ep___antennas_create from './endpoints/antennas/create.js';
import * as ep___antennas_delete from './endpoints/antennas/delete.js';
import * as ep___antennas_list from './endpoints/antennas/list.js';
import * as ep___antennas_notes from './endpoints/antennas/notes.js';
import * as ep___antennas_show from './endpoints/antennas/show.js';
import * as ep___antennas_update from './endpoints/antennas/update.js';
import * as ep___ap_get from './endpoints/ap/get.js';
import * as ep___ap_show from './endpoints/ap/show.js';
import * as ep___app_create from './endpoints/app/create.js';
import * as ep___app_show from './endpoints/app/show.js';
import * as ep___auth_accept from './endpoints/auth/accept.js';
import * as ep___auth_session_generate from './endpoints/auth/session/generate.js';
import * as ep___auth_session_show from './endpoints/auth/session/show.js';
import * as ep___auth_session_userkey from './endpoints/auth/session/userkey.js';
import * as ep___blocking_create from './endpoints/blocking/create.js';
import * as ep___blocking_delete from './endpoints/blocking/delete.js';
import * as ep___blocking_list from './endpoints/blocking/list.js';
import * as ep___channels_create from './endpoints/channels/create.js';
import * as ep___channels_featured from './endpoints/channels/featured.js';
import * as ep___channels_follow from './endpoints/channels/follow.js';
import * as ep___channels_followed from './endpoints/channels/followed.js';
import * as ep___channels_owned from './endpoints/channels/owned.js';
import * as ep___channels_show from './endpoints/channels/show.js';
import * as ep___channels_timeline from './endpoints/channels/timeline.js';
import * as ep___channels_unfollow from './endpoints/channels/unfollow.js';
import * as ep___channels_update from './endpoints/channels/update.js';
import * as ep___charts_activeUsers from './endpoints/charts/active-users.js';
import * as ep___charts_apRequest from './endpoints/charts/ap-request.js';
import * as ep___charts_drive from './endpoints/charts/drive.js';
import * as ep___charts_federation from './endpoints/charts/federation.js';
import * as ep___charts_hashtag from './endpoints/charts/hashtag.js';
import * as ep___charts_instance from './endpoints/charts/instance.js';
import * as ep___charts_notes from './endpoints/charts/notes.js';
import * as ep___charts_user_drive from './endpoints/charts/user/drive.js';
import * as ep___charts_user_following from './endpoints/charts/user/following.js';
import * as ep___charts_user_notes from './endpoints/charts/user/notes.js';
import * as ep___charts_user_reactions from './endpoints/charts/user/reactions.js';
import * as ep___charts_users from './endpoints/charts/users.js';
import * as ep___clips_addNote from './endpoints/clips/add-note.js';
import * as ep___clips_removeNote from './endpoints/clips/remove-note.js';
import * as ep___clips_create from './endpoints/clips/create.js';
import * as ep___clips_delete from './endpoints/clips/delete.js';
import * as ep___clips_list from './endpoints/clips/list.js';
import * as ep___clips_notes from './endpoints/clips/notes.js';
import * as ep___clips_show from './endpoints/clips/show.js';
import * as ep___clips_update from './endpoints/clips/update.js';
import * as ep___drive from './endpoints/drive.js';
import * as ep___drive_files from './endpoints/drive/files.js';
import * as ep___drive_files_attachedNotes from './endpoints/drive/files/attached-notes.js';
import * as ep___drive_files_checkExistence from './endpoints/drive/files/check-existence.js';
import * as ep___drive_files_create from './endpoints/drive/files/create.js';
import * as ep___drive_files_delete from './endpoints/drive/files/delete.js';
import * as ep___drive_files_findByHash from './endpoints/drive/files/find-by-hash.js';
import * as ep___drive_files_find from './endpoints/drive/files/find.js';
import * as ep___drive_files_show from './endpoints/drive/files/show.js';
import * as ep___drive_files_update from './endpoints/drive/files/update.js';
import * as ep___drive_files_uploadFromUrl from './endpoints/drive/files/upload-from-url.js';
import * as ep___drive_folders from './endpoints/drive/folders.js';
import * as ep___drive_folders_create from './endpoints/drive/folders/create.js';
import * as ep___drive_folders_delete from './endpoints/drive/folders/delete.js';
import * as ep___drive_folders_find from './endpoints/drive/folders/find.js';
import * as ep___drive_folders_show from './endpoints/drive/folders/show.js';
import * as ep___drive_folders_update from './endpoints/drive/folders/update.js';
import * as ep___drive_stream from './endpoints/drive/stream.js';
import * as ep___emailAddress_available from './endpoints/email-address/available.js';
import * as ep___endpoint from './endpoints/endpoint.js';
import * as ep___endpoints from './endpoints/endpoints.js';
import * as ep___exportCustomEmojis from './endpoints/export-custom-emojis.js';
import * as ep___federation_followers from './endpoints/federation/followers.js';
import * as ep___federation_following from './endpoints/federation/following.js';
import * as ep___federation_instances from './endpoints/federation/instances.js';
import * as ep___federation_showInstance from './endpoints/federation/show-instance.js';
import * as ep___federation_updateRemoteUser from './endpoints/federation/update-remote-user.js';
import * as ep___federation_users from './endpoints/federation/users.js';
import * as ep___federation_stats from './endpoints/federation/stats.js';
import * as ep___following_create from './endpoints/following/create.js';
import * as ep___following_delete from './endpoints/following/delete.js';
import * as ep___following_invalidate from './endpoints/following/invalidate.js';
import * as ep___following_requests_accept from './endpoints/following/requests/accept.js';
import * as ep___following_requests_cancel from './endpoints/following/requests/cancel.js';
import * as ep___following_requests_list from './endpoints/following/requests/list.js';
import * as ep___following_requests_reject from './endpoints/following/requests/reject.js';
import * as ep___gallery_featured from './endpoints/gallery/featured.js';
import * as ep___gallery_popular from './endpoints/gallery/popular.js';
import * as ep___gallery_posts from './endpoints/gallery/posts.js';
import * as ep___gallery_posts_create from './endpoints/gallery/posts/create.js';
import * as ep___gallery_posts_delete from './endpoints/gallery/posts/delete.js';
import * as ep___gallery_posts_like from './endpoints/gallery/posts/like.js';
import * as ep___gallery_posts_show from './endpoints/gallery/posts/show.js';
import * as ep___gallery_posts_unlike from './endpoints/gallery/posts/unlike.js';
import * as ep___gallery_posts_update from './endpoints/gallery/posts/update.js';
import * as ep___getOnlineUsersCount from './endpoints/get-online-users-count.js';
import * as ep___hashtags_list from './endpoints/hashtags/list.js';
import * as ep___hashtags_search from './endpoints/hashtags/search.js';
import * as ep___hashtags_show from './endpoints/hashtags/show.js';
import * as ep___hashtags_trend from './endpoints/hashtags/trend.js';
import * as ep___hashtags_users from './endpoints/hashtags/users.js';
import * as ep___i from './endpoints/i.js';
import * as ep___i_2fa_done from './endpoints/i/2fa/done.js';
import * as ep___i_2fa_keyDone from './endpoints/i/2fa/key-done.js';
import * as ep___i_2fa_passwordLess from './endpoints/i/2fa/password-less.js';
import * as ep___i_2fa_registerKey from './endpoints/i/2fa/register-key.js';
import * as ep___i_2fa_register from './endpoints/i/2fa/register.js';
import * as ep___i_2fa_removeKey from './endpoints/i/2fa/remove-key.js';
import * as ep___i_2fa_unregister from './endpoints/i/2fa/unregister.js';
import * as ep___i_apps from './endpoints/i/apps.js';
import * as ep___i_authorizedApps from './endpoints/i/authorized-apps.js';
import * as ep___i_changePassword from './endpoints/i/change-password.js';
import * as ep___i_deleteAccount from './endpoints/i/delete-account.js';
import * as ep___i_exportBlocking from './endpoints/i/export-blocking.js';
import * as ep___i_exportFollowing from './endpoints/i/export-following.js';
import * as ep___i_exportMute from './endpoints/i/export-mute.js';
import * as ep___i_exportNotes from './endpoints/i/export-notes.js';
import * as ep___i_exportUserLists from './endpoints/i/export-user-lists.js';
import * as ep___i_favorites from './endpoints/i/favorites.js';
import * as ep___i_gallery_likes from './endpoints/i/gallery/likes.js';
import * as ep___i_gallery_posts from './endpoints/i/gallery/posts.js';
import * as ep___i_getWordMutedNotesCount from './endpoints/i/get-word-muted-notes-count.js';
import * as ep___i_importBlocking from './endpoints/i/import-blocking.js';
import * as ep___i_importFollowing from './endpoints/i/import-following.js';
import * as ep___i_importMuting from './endpoints/i/import-muting.js';
import * as ep___i_importUserLists from './endpoints/i/import-user-lists.js';
import * as ep___i_notifications from './endpoints/i/notifications.js';
import * as ep___i_pageLikes from './endpoints/i/page-likes.js';
import * as ep___i_pages from './endpoints/i/pages.js';
import * as ep___i_pin from './endpoints/i/pin.js';
import * as ep___i_readAllMessagingMessages from './endpoints/i/read-all-messaging-messages.js';
import * as ep___i_readAllUnreadNotes from './endpoints/i/read-all-unread-notes.js';
import * as ep___i_readAnnouncement from './endpoints/i/read-announcement.js';
import * as ep___i_regenerateToken from './endpoints/i/regenerate-token.js';
import * as ep___i_registry_getAll from './endpoints/i/registry/get-all.js';
import * as ep___i_registry_getDetail from './endpoints/i/registry/get-detail.js';
import * as ep___i_registry_get from './endpoints/i/registry/get.js';
import * as ep___i_registry_keysWithType from './endpoints/i/registry/keys-with-type.js';
import * as ep___i_registry_keys from './endpoints/i/registry/keys.js';
import * as ep___i_registry_remove from './endpoints/i/registry/remove.js';
import * as ep___i_registry_scopes from './endpoints/i/registry/scopes.js';
import * as ep___i_registry_set from './endpoints/i/registry/set.js';
import * as ep___i_revokeToken from './endpoints/i/revoke-token.js';
import * as ep___i_signinHistory from './endpoints/i/signin-history.js';
import * as ep___i_unpin from './endpoints/i/unpin.js';
import * as ep___i_updateEmail from './endpoints/i/update-email.js';
import * as ep___i_update from './endpoints/i/update.js';
import * as ep___i_userGroupInvites from './endpoints/i/user-group-invites.js';
import * as ep___i_webhooks_create from './endpoints/i/webhooks/create.js';
import * as ep___i_webhooks_show from './endpoints/i/webhooks/show.js';
import * as ep___i_webhooks_list from './endpoints/i/webhooks/list.js';
import * as ep___i_webhooks_update from './endpoints/i/webhooks/update.js';
import * as ep___i_webhooks_delete from './endpoints/i/webhooks/delete.js';
import * as ep___messaging_history from './endpoints/messaging/history.js';
import * as ep___messaging_messages from './endpoints/messaging/messages.js';
import * as ep___messaging_messages_create from './endpoints/messaging/messages/create.js';
import * as ep___messaging_messages_delete from './endpoints/messaging/messages/delete.js';
import * as ep___messaging_messages_read from './endpoints/messaging/messages/read.js';
import * as ep___meta from './endpoints/meta.js';
import * as ep___miauth_genToken from './endpoints/miauth/gen-token.js';
import * as ep___mute_create from './endpoints/mute/create.js';
import * as ep___mute_delete from './endpoints/mute/delete.js';
import * as ep___mute_list from './endpoints/mute/list.js';
import * as ep___my_apps from './endpoints/my/apps.js';
import * as ep___notes from './endpoints/notes.js';
import * as ep___notes_children from './endpoints/notes/children.js';
import * as ep___notes_clips from './endpoints/notes/clips.js';
import * as ep___notes_conversation from './endpoints/notes/conversation.js';
import * as ep___notes_create from './endpoints/notes/create.js';
import * as ep___notes_delete from './endpoints/notes/delete.js';
import * as ep___notes_favorites_create from './endpoints/notes/favorites/create.js';
import * as ep___notes_favorites_delete from './endpoints/notes/favorites/delete.js';
import * as ep___notes_featured from './endpoints/notes/featured.js';
import * as ep___notes_globalTimeline from './endpoints/notes/global-timeline.js';
import * as ep___notes_hybridTimeline from './endpoints/notes/hybrid-timeline.js';
import * as ep___notes_localTimeline from './endpoints/notes/local-timeline.js';
import * as ep___notes_mentions from './endpoints/notes/mentions.js';
import * as ep___notes_polls_recommendation from './endpoints/notes/polls/recommendation.js';
import * as ep___notes_polls_vote from './endpoints/notes/polls/vote.js';
import * as ep___notes_reactions from './endpoints/notes/reactions.js';
import * as ep___notes_reactions_create from './endpoints/notes/reactions/create.js';
import * as ep___notes_reactions_delete from './endpoints/notes/reactions/delete.js';
import * as ep___notes_renotes from './endpoints/notes/renotes.js';
import * as ep___notes_replies from './endpoints/notes/replies.js';
import * as ep___notes_searchByTag from './endpoints/notes/search-by-tag.js';
import * as ep___notes_search from './endpoints/notes/search.js';
import * as ep___notes_show from './endpoints/notes/show.js';
import * as ep___notes_state from './endpoints/notes/state.js';
import * as ep___notes_threadMuting_create from './endpoints/notes/thread-muting/create.js';
import * as ep___notes_threadMuting_delete from './endpoints/notes/thread-muting/delete.js';
import * as ep___notes_timeline from './endpoints/notes/timeline.js';
import * as ep___notes_translate from './endpoints/notes/translate.js';
import * as ep___notes_unrenote from './endpoints/notes/unrenote.js';
import * as ep___notes_userListTimeline from './endpoints/notes/user-list-timeline.js';
import * as ep___notifications_create from './endpoints/notifications/create.js';
import * as ep___notifications_markAllAsRead from './endpoints/notifications/mark-all-as-read.js';
import * as ep___notifications_read from './endpoints/notifications/read.js';
import * as ep___pagePush from './endpoints/page-push.js';
import * as ep___pages_create from './endpoints/pages/create.js';
import * as ep___pages_delete from './endpoints/pages/delete.js';
import * as ep___pages_featured from './endpoints/pages/featured.js';
import * as ep___pages_like from './endpoints/pages/like.js';
import * as ep___pages_show from './endpoints/pages/show.js';
import * as ep___pages_unlike from './endpoints/pages/unlike.js';
import * as ep___pages_update from './endpoints/pages/update.js';
import * as ep___ping from './endpoints/ping.js';
import * as ep___pinnedUsers from './endpoints/pinned-users.js';
import * as ep___promo_read from './endpoints/promo/read.js';
import * as ep___requestResetPassword from './endpoints/request-reset-password.js';
import * as ep___resetDb from './endpoints/reset-db.js';
import * as ep___resetPassword from './endpoints/reset-password.js';
import * as ep___serverInfo from './endpoints/server-info.js';
import * as ep___stats from './endpoints/stats.js';
import * as ep___sw_register from './endpoints/sw/register.js';
import * as ep___sw_unregister from './endpoints/sw/unregister.js';
import * as ep___test from './endpoints/test.js';
import * as ep___username_available from './endpoints/username/available.js';
import * as ep___users from './endpoints/users.js';
import * as ep___users_clips from './endpoints/users/clips.js';
import * as ep___users_followers from './endpoints/users/followers.js';
import * as ep___users_following from './endpoints/users/following.js';
import * as ep___users_gallery_posts from './endpoints/users/gallery/posts.js';
import * as ep___users_getFrequentlyRepliedUsers from './endpoints/users/get-frequently-replied-users.js';
import * as ep___users_groups_create from './endpoints/users/groups/create.js';
import * as ep___users_groups_delete from './endpoints/users/groups/delete.js';
import * as ep___users_groups_invitations_accept from './endpoints/users/groups/invitations/accept.js';
import * as ep___users_groups_invitations_reject from './endpoints/users/groups/invitations/reject.js';
import * as ep___users_groups_invite from './endpoints/users/groups/invite.js';
import * as ep___users_groups_joined from './endpoints/users/groups/joined.js';
import * as ep___users_groups_leave from './endpoints/users/groups/leave.js';
import * as ep___users_groups_owned from './endpoints/users/groups/owned.js';
import * as ep___users_groups_pull from './endpoints/users/groups/pull.js';
import * as ep___users_groups_show from './endpoints/users/groups/show.js';
import * as ep___users_groups_transfer from './endpoints/users/groups/transfer.js';
import * as ep___users_groups_update from './endpoints/users/groups/update.js';
import * as ep___users_lists_create from './endpoints/users/lists/create.js';
import * as ep___users_lists_delete from './endpoints/users/lists/delete.js';
import * as ep___users_lists_list from './endpoints/users/lists/list.js';
import * as ep___users_lists_pull from './endpoints/users/lists/pull.js';
import * as ep___users_lists_push from './endpoints/users/lists/push.js';
import * as ep___users_lists_show from './endpoints/users/lists/show.js';
import * as ep___users_lists_update from './endpoints/users/lists/update.js';
import * as ep___users_notes from './endpoints/users/notes.js';
import * as ep___users_pages from './endpoints/users/pages.js';
import * as ep___users_reactions from './endpoints/users/reactions.js';
import * as ep___users_recommendation from './endpoints/users/recommendation.js';
import * as ep___users_relation from './endpoints/users/relation.js';
import * as ep___users_reportAbuse from './endpoints/users/report-abuse.js';
import * as ep___users_searchByUsernameAndHost from './endpoints/users/search-by-username-and-host.js';
import * as ep___users_search from './endpoints/users/search.js';
import * as ep___users_show from './endpoints/users/show.js';
import * as ep___users_stats from './endpoints/users/stats.js';
import * as ep___fetchRss from './endpoints/fetch-rss.js';
import * as ep___admin_driveCapOverride from './endpoints/admin/drive-capacity-override.js';
import { GetterService } from './common/GetterService.js';

@Module({
	imports: [
		CoreModule,
	],
	providers: [
		GetterService,
		{ provide: 'ep:admin/meta', useClass: ep___admin_meta.default },
		{ provide: 'ep:admin/abuse-user-reports', useClass: ep___admin_abuseUserReports.default },
		{ provide: 'ep:admin/accounts/create', useClass: ep___admin_accounts_create.default },
		{ provide: 'ep:admin/accounts/delete', useClass: ep___admin_accounts_delete.default },
		{ provide: 'ep:admin/ad/create', useClass: ep___admin_ad_create.default },
		{ provide: 'ep:admin/ad/delete', useClass: ep___admin_ad_delete.default },
		{ provide: 'ep:admin/ad/list', useClass: ep___admin_ad_list.default },
		{ provide: 'ep:admin/ad/update', useClass: ep___admin_ad_update.default },
		{ provide: 'ep:admin/announcements/create', useClass: ep___admin_announcements_create.default },
		{ provide: 'ep:admin/announcements/delete', useClass: ep___admin_announcements_delete.default },
		{ provide: 'ep:admin/announcements/list', useClass: ep___admin_announcements_list.default },
		{ provide: 'ep:admin/announcements/update', useClass: ep___admin_announcements_update.default },
		{ provide: 'ep:admin/delete-all-files-of-a-user', useClass: ep___admin_deleteAllFilesOfAUser.default },
		{ provide: 'ep:admin/drive/clean-remote-files', useClass: ep___admin_drive_cleanRemoteFiles.default },
		{ provide: 'ep:admin/drive/cleanup', useClass: ep___admin_drive_cleanup.default },
		{ provide: 'ep:admin/drive/files', useClass: ep___admin_drive_files.default },
		{ provide: 'ep:admin/drive/show-file', useClass: ep___admin_drive_showFile.default },
		{ provide: 'ep:admin/emoji/add-aliases-bulk', useClass: ep___admin_emoji_addAliasesBulk.default },
		{ provide: 'ep:admin/emoji/add', useClass: ep___admin_emoji_add.default },
		{ provide: 'ep:admin/emoji/copy', useClass: ep___admin_emoji_copy.default },
		{ provide: 'ep:admin/emoji/delete-bulk', useClass: ep___admin_emoji_deleteBulk.default },
		{ provide: 'ep:admin/emoji/delete', useClass: ep___admin_emoji_delete.default },
		{ provide: 'ep:admin/emoji/import-zip', useClass: ep___admin_emoji_importZip.default },
		{ provide: 'ep:admin/emoji/list-remote', useClass: ep___admin_emoji_listRemote.default },
		{ provide: 'ep:admin/emoji/list', useClass: ep___admin_emoji_list.default },
		{ provide: 'ep:admin/emoji/remove-aliases-bulk', useClass: ep___admin_emoji_removeAliasesBulk.default },
		{ provide: 'ep:admin/emoji/set-aliases-bulk', useClass: ep___admin_emoji_setAliasesBulk.default },
		{ provide: 'ep:admin/emoji/set-category-bulk', useClass: ep___admin_emoji_setCategoryBulk.default },
		{ provide: 'ep:admin/emoji/update', useClass: ep___admin_emoji_update.default },
		{ provide: 'ep:admin/federation/delete-all-files', useClass: ep___admin_federation_deleteAllFiles.default },
		{ provide: 'ep:admin/federation/refresh-remote-instance-metadata', useClass: ep___admin_federation_refreshRemoteInstanceMetadata.default },
		{ provide: 'ep:admin/federation/remove-all-following', useClass: ep___admin_federation_removeAllFollowing.default },
		{ provide: 'ep:admin/federation/update-instance', useClass: ep___admin_federation_updateInstance.default },
		{ provide: 'ep:admin/get-index-stats', useClass: ep___admin_getIndexStats.default },
		{ provide: 'ep:admin/get-table-stats', useClass: ep___admin_getTableStats.default },
		{ provide: 'ep:admin/get-user-ips', useClass: ep___admin_getUserIps.default },
		{ provide: 'ep:admin/invite', useClass: ep___admin_invite.default },
		{ provide: 'ep:admin/moderators/add', useClass: ep___admin_moderators_add.default },
		{ provide: 'ep:admin/moderators/remove', useClass: ep___admin_moderators_remove.default },
		{ provide: 'ep:admin/promo/create', useClass: ep___admin_promo_create.default },
		{ provide: 'ep:admin/queue/clear', useClass: ep___admin_queue_clear.default },
		{ provide: 'ep:admin/queue/deliver-delayed', useClass: ep___admin_queue_deliverDelayed.default },
		{ provide: 'ep:admin/queue/inbox-delayed', useClass: ep___admin_queue_inboxDelayed.default },
		{ provide: 'ep:admin/queue/stats', useClass: ep___admin_queue_stats.default },
		{ provide: 'ep:admin/relays/add', useClass: ep___admin_relays_add.default },
		{ provide: 'ep:admin/relays/list', useClass: ep___admin_relays_list.default },
		{ provide: 'ep:admin/relays/remove', useClass: ep___admin_relays_remove.default },
		{ provide: 'ep:admin/reset-password', useClass: ep___admin_resetPassword.default },
		{ provide: 'ep:admin/resolve-abuse-user-report', useClass: ep___admin_resolveAbuseUserReport.default },
		{ provide: 'ep:admin/send-email', useClass: ep___admin_sendEmail.default },
		{ provide: 'ep:admin/server-info', useClass: ep___admin_serverInfo.default },
		{ provide: 'ep:admin/show-moderation-logs', useClass: ep___admin_showModerationLogs.default },
		{ provide: 'ep:admin/show-user', useClass: ep___admin_showUser.default },
		{ provide: 'ep:admin/show-users', useClass: ep___admin_showUsers.default },
		{ provide: 'ep:admin/silence-user', useClass: ep___admin_silenceUser.default },
		{ provide: 'ep:admin/suspend-user', useClass: ep___admin_suspendUser.default },
		{ provide: 'ep:admin/unsilence-user', useClass: ep___admin_unsilenceUser.default },
		{ provide: 'ep:admin/unsuspend-user', useClass: ep___admin_unsuspendUser.default },
		{ provide: 'ep:admin/update-meta', useClass: ep___admin_updateMeta.default },
		{ provide: 'ep:admin/delete-account', useClass: ep___admin_deleteAccount.default },
		{ provide: 'ep:admin/update-user-note', useClass: ep___admin_updateUserNote.default },
		{ provide: 'ep:announcements', useClass: ep___announcements.default },
		{ provide: 'ep:antennas/create', useClass: ep___antennas_create.default },
		{ provide: 'ep:antennas/delete', useClass: ep___antennas_delete.default },
		{ provide: 'ep:antennas/list', useClass: ep___antennas_list.default },
		{ provide: 'ep:antennas/notes', useClass: ep___antennas_notes.default },
		{ provide: 'ep:antennas/show', useClass: ep___antennas_show.default },
		{ provide: 'ep:antennas/update', useClass: ep___antennas_update.default },
		{ provide: 'ep:ap/get', useClass: ep___ap_get.default },
		{ provide: 'ep:ap/show', useClass: ep___ap_show.default },
		{ provide: 'ep:app/create', useClass: ep___app_create.default },
		{ provide: 'ep:app/show', useClass: ep___app_show.default },
		{ provide: 'ep:auth/accept', useClass: ep___auth_accept.default },
		{ provide: 'ep:auth/session/generate', useClass: ep___auth_session_generate.default },
		{ provide: 'ep:auth/session/show', useClass: ep___auth_session_show.default },
		{ provide: 'ep:auth/session/userkey', useClass: ep___auth_session_userkey.default },
		{ provide: 'ep:blocking/create', useClass: ep___blocking_create.default },
		{ provide: 'ep:blocking/delete', useClass: ep___blocking_delete.default },
		{ provide: 'ep:blocking/list', useClass: ep___blocking_list.default },
		{ provide: 'ep:channels/create', useClass: ep___channels_create.default },
		{ provide: 'ep:channels/featured', useClass: ep___channels_featured.default },
		{ provide: 'ep:channels/follow', useClass: ep___channels_follow.default },
		{ provide: 'ep:channels/followed', useClass: ep___channels_followed.default },
		{ provide: 'ep:channels/owned', useClass: ep___channels_owned.default },
		{ provide: 'ep:channels/show', useClass: ep___channels_show.default },
		{ provide: 'ep:channels/timeline', useClass: ep___channels_timeline.default },
		{ provide: 'ep:channels/unfollow', useClass: ep___channels_unfollow.default },
		{ provide: 'ep:channels/update', useClass: ep___channels_update.default },
		{ provide: 'ep:charts/active-users', useClass: ep___charts_activeUsers.default },
		{ provide: 'ep:charts/ap-request', useClass: ep___charts_apRequest.default },
		{ provide: 'ep:charts/drive', useClass: ep___charts_drive.default },
		{ provide: 'ep:charts/federation', useClass: ep___charts_federation.default },
		{ provide: 'ep:charts/hashtag', useClass: ep___charts_hashtag.default },
		{ provide: 'ep:charts/instance', useClass: ep___charts_instance.default },
		{ provide: 'ep:charts/notes', useClass: ep___charts_notes.default },
		{ provide: 'ep:charts/user/drive', useClass: ep___charts_user_drive.default },
		{ provide: 'ep:charts/user/following', useClass: ep___charts_user_following.default },
		{ provide: 'ep:charts/user/notes', useClass: ep___charts_user_notes.default },
		{ provide: 'ep:charts/user/reactions', useClass: ep___charts_user_reactions.default },
		{ provide: 'ep:charts/users', useClass: ep___charts_users.default },
		{ provide: 'ep:clips/add-note', useClass: ep___clips_addNote.default },
		{ provide: 'ep:clips/remove-note', useClass: ep___clips_removeNote.default },
		{ provide: 'ep:clips/create', useClass: ep___clips_create.default },
		{ provide: 'ep:clips/delete', useClass: ep___clips_delete.default },
		{ provide: 'ep:clips/list', useClass: ep___clips_list.default },
		{ provide: 'ep:clips/notes', useClass: ep___clips_notes.default },
		{ provide: 'ep:clips/show', useClass: ep___clips_show.default },
		{ provide: 'ep:clips/update', useClass: ep___clips_update.default },
		{ provide: 'ep:drive', useClass: ep___drive.default },
		{ provide: 'ep:drive/files', useClass: ep___drive_files.default },
		{ provide: 'ep:drive/files/attached-notes', useClass: ep___drive_files_attachedNotes.default },
		{ provide: 'ep:drive/files/check-existence', useClass: ep___drive_files_checkExistence.default },
		{ provide: 'ep:drive/files/create', useClass: ep___drive_files_create.default },
		{ provide: 'ep:drive/files/delete', useClass: ep___drive_files_delete.default },
		{ provide: 'ep:drive/files/find-by-hash', useClass: ep___drive_files_findByHash.default },
		{ provide: 'ep:drive/files/find', useClass: ep___drive_files_find.default },
		{ provide: 'ep:drive/files/show', useClass: ep___drive_files_show.default },
		{ provide: 'ep:drive/files/update', useClass: ep___drive_files_update.default },
		{ provide: 'ep:drive/files/upload-from-url', useClass: ep___drive_files_uploadFromUrl.default },
		{ provide: 'ep:drive/folders', useClass: ep___drive_folders.default },
		{ provide: 'ep:drive/folders/create', useClass: ep___drive_folders_create.default },
		{ provide: 'ep:drive/folders/delete', useClass: ep___drive_folders_delete.default },
		{ provide: 'ep:drive/folders/find', useClass: ep___drive_folders_find.default },
		{ provide: 'ep:drive/folders/show', useClass: ep___drive_folders_show.default },
		{ provide: 'ep:drive/folders/update', useClass: ep___drive_folders_update.default },
		{ provide: 'ep:drive/stream', useClass: ep___drive_stream.default },
		{ provide: 'ep:email-address/available', useClass: ep___emailAddress_available.default },
		{ provide: 'ep:endpoint', useClass: ep___endpoint.default },
		{ provide: 'ep:endpoints', useClass: ep___endpoints.default },
		{ provide: 'ep:export-custom-emojis', useClass: ep___exportCustomEmojis.default },
		{ provide: 'ep:federation/followers', useClass: ep___federation_followers.default },
		{ provide: 'ep:federation/following', useClass: ep___federation_following.default },
		{ provide: 'ep:federation/instances', useClass: ep___federation_instances.default },
		{ provide: 'ep:federation/show-instance', useClass: ep___federation_showInstance.default },
		{ provide: 'ep:federation/update-remote-user', useClass: ep___federation_updateRemoteUser.default },
		{ provide: 'ep:federation/users', useClass: ep___federation_users.default },
		{ provide: 'ep:federation/stats', useClass: ep___federation_stats.default },
		{ provide: 'ep:following/create', useClass: ep___following_create.default },
		{ provide: 'ep:following/delete', useClass: ep___following_delete.default },
		{ provide: 'ep:following/invalidate', useClass: ep___following_invalidate.default },
		{ provide: 'ep:following/requests/accept', useClass: ep___following_requests_accept.default },
		{ provide: 'ep:following/requests/cancel', useClass: ep___following_requests_cancel.default },
		{ provide: 'ep:following/requests/list', useClass: ep___following_requests_list.default },
		{ provide: 'ep:following/requests/reject', useClass: ep___following_requests_reject.default },
		{ provide: 'ep:gallery/featured', useClass: ep___gallery_featured.default },
		{ provide: 'ep:gallery/popular', useClass: ep___gallery_popular.default },
		{ provide: 'ep:gallery/posts', useClass: ep___gallery_posts.default },
		{ provide: 'ep:gallery/posts/create', useClass: ep___gallery_posts_create.default },
		{ provide: 'ep:gallery/posts/delete', useClass: ep___gallery_posts_delete.default },
		{ provide: 'ep:gallery/posts/like', useClass: ep___gallery_posts_like.default },
		{ provide: 'ep:gallery/posts/show', useClass: ep___gallery_posts_show.default },
		{ provide: 'ep:gallery/posts/unlike', useClass: ep___gallery_posts_unlike.default },
		{ provide: 'ep:gallery/posts/update', useClass: ep___gallery_posts_update.default },
		{ provide: 'ep:get-online-users-count', useClass: ep___getOnlineUsersCount.default },
		{ provide: 'ep:hashtags/list', useClass: ep___hashtags_list.default },
		{ provide: 'ep:hashtags/search', useClass: ep___hashtags_search.default },
		{ provide: 'ep:hashtags/show', useClass: ep___hashtags_show.default },
		{ provide: 'ep:hashtags/trend', useClass: ep___hashtags_trend.default },
		{ provide: 'ep:hashtags/users', useClass: ep___hashtags_users.default },
		{ provide: 'ep:i', useClass: ep___i.default },
		{ provide: 'ep:i/2fa/done', useClass: ep___i_2fa_done.default },
		{ provide: 'ep:i/2fa/key-done', useClass: ep___i_2fa_keyDone.default },
		{ provide: 'ep:i/2fa/password-less', useClass: ep___i_2fa_passwordLess.default },
		{ provide: 'ep:i/2fa/register-key', useClass: ep___i_2fa_registerKey.default },
		{ provide: 'ep:i/2fa/register', useClass: ep___i_2fa_register.default },
		{ provide: 'ep:i/2fa/remove-key', useClass: ep___i_2fa_removeKey.default },
		{ provide: 'ep:i/2fa/unregister', useClass: ep___i_2fa_unregister.default },
		{ provide: 'ep:i/apps', useClass: ep___i_apps.default },
		{ provide: 'ep:i/authorized-apps', useClass: ep___i_authorizedApps.default },
		{ provide: 'ep:i/change-password', useClass: ep___i_changePassword.default },
		{ provide: 'ep:i/delete-account', useClass: ep___i_deleteAccount.default },
		{ provide: 'ep:i/export-blocking', useClass: ep___i_exportBlocking.default },
		{ provide: 'ep:i/export-following', useClass: ep___i_exportFollowing.default },
		{ provide: 'ep:i/export-mute', useClass: ep___i_exportMute.default },
		{ provide: 'ep:i/export-notes', useClass: ep___i_exportNotes.default },
		{ provide: 'ep:i/export-user-lists', useClass: ep___i_exportUserLists.default },
		{ provide: 'ep:i/favorites', useClass: ep___i_favorites.default },
		{ provide: 'ep:i/gallery/likes', useClass: ep___i_gallery_likes.default },
		{ provide: 'ep:i/gallery/posts', useClass: ep___i_gallery_posts.default },
		{ provide: 'ep:i/get-word-muted-notes-count', useClass: ep___i_getWordMutedNotesCount.default },
		{ provide: 'ep:i/import-blocking', useClass: ep___i_importBlocking.default },
		{ provide: 'ep:i/import-following', useClass: ep___i_importFollowing.default },
		{ provide: 'ep:i/import-muting', useClass: ep___i_importMuting.default },
		{ provide: 'ep:i/import-user-lists', useClass: ep___i_importUserLists.default },
		{ provide: 'ep:i/notifications', useClass: ep___i_notifications.default },
		{ provide: 'ep:i/page-likes', useClass: ep___i_pageLikes.default },
		{ provide: 'ep:i/pages', useClass: ep___i_pages.default },
		{ provide: 'ep:i/pin', useClass: ep___i_pin.default },
		{ provide: 'ep:i/read-all-messaging-messages', useClass: ep___i_readAllMessagingMessages.default },
		{ provide: 'ep:i/read-all-unread-notes', useClass: ep___i_readAllUnreadNotes.default },
		{ provide: 'ep:i/read-announcement', useClass: ep___i_readAnnouncement.default },
		{ provide: 'ep:i/regenerate-token', useClass: ep___i_regenerateToken.default },
		{ provide: 'ep:i/registry/get-all', useClass: ep___i_registry_getAll.default },
		{ provide: 'ep:i/registry/get-detail', useClass: ep___i_registry_getDetail.default },
		{ provide: 'ep:i/registry/get', useClass: ep___i_registry_get.default },
		{ provide: 'ep:i/registry/keys-with-type', useClass: ep___i_registry_keysWithType.default },
		{ provide: 'ep:i/registry/keys', useClass: ep___i_registry_keys.default },
		{ provide: 'ep:i/registry/remove', useClass: ep___i_registry_remove.default },
		{ provide: 'ep:i/registry/scopes', useClass: ep___i_registry_scopes.default },
		{ provide: 'ep:i/registry/set', useClass: ep___i_registry_set.default },
		{ provide: 'ep:i/revoke-token', useClass: ep___i_revokeToken.default },
		{ provide: 'ep:i/signin-history', useClass: ep___i_signinHistory.default },
		{ provide: 'ep:i/unpin', useClass: ep___i_unpin.default },
		{ provide: 'ep:i/update-email', useClass: ep___i_updateEmail.default },
		{ provide: 'ep:i/update', useClass: ep___i_update.default },
		{ provide: 'ep:i/user-group-invites', useClass: ep___i_userGroupInvites.default },
		{ provide: 'ep:i/webhooks/create', useClass: ep___i_webhooks_create.default },
		{ provide: 'ep:i/webhooks/list', useClass: ep___i_webhooks_list.default },
		{ provide: 'ep:i/webhooks/show', useClass: ep___i_webhooks_show.default },
		{ provide: 'ep:i/webhooks/update', useClass: ep___i_webhooks_update.default },
		{ provide: 'ep:i/webhooks/delete', useClass: ep___i_webhooks_delete.default },
		{ provide: 'ep:messaging/history', useClass: ep___messaging_history.default },
		{ provide: 'ep:messaging/messages', useClass: ep___messaging_messages.default },
		{ provide: 'ep:messaging/messages/create', useClass: ep___messaging_messages_create.default },
		{ provide: 'ep:messaging/messages/delete', useClass: ep___messaging_messages_delete.default },
		{ provide: 'ep:messaging/messages/read', useClass: ep___messaging_messages_read.default },
		{ provide: 'ep:meta', useClass: ep___meta.default },
		{ provide: 'ep:miauth/gen-token', useClass: ep___miauth_genToken.default },
		{ provide: 'ep:mute/create', useClass: ep___mute_create.default },
		{ provide: 'ep:mute/delete', useClass: ep___mute_delete.default },
		{ provide: 'ep:mute/list', useClass: ep___mute_list.default },
		{ provide: 'ep:my/apps', useClass: ep___my_apps.default },
		{ provide: 'ep:notes', useClass: ep___notes.default },
		{ provide: 'ep:notes/children', useClass: ep___notes_children.default },
		{ provide: 'ep:notes/clips', useClass: ep___notes_clips.default },
		{ provide: 'ep:notes/conversation', useClass: ep___notes_conversation.default },
		{ provide: 'ep:notes/create', useClass: ep___notes_create.default },
		{ provide: 'ep:notes/delete', useClass: ep___notes_delete.default },
		{ provide: 'ep:notes/favorites/create', useClass: ep___notes_favorites_create.default },
		{ provide: 'ep:notes/favorites/delete', useClass: ep___notes_favorites_delete.default },
		{ provide: 'ep:notes/featured', useClass: ep___notes_featured.default },
		{ provide: 'ep:notes/global-timeline', useClass: ep___notes_globalTimeline.default },
		{ provide: 'ep:notes/hybrid-timeline', useClass: ep___notes_hybridTimeline.default },
		{ provide: 'ep:notes/local-timeline', useClass: ep___notes_localTimeline.default },
		{ provide: 'ep:notes/mentions', useClass: ep___notes_mentions.default },
		{ provide: 'ep:notes/polls/recommendation', useClass: ep___notes_polls_recommendation.default },
		{ provide: 'ep:notes/polls/vote', useClass: ep___notes_polls_vote.default },
		{ provide: 'ep:notes/reactions', useClass: ep___notes_reactions.default },
		{ provide: 'ep:notes/reactions/create', useClass: ep___notes_reactions_create.default },
		{ provide: 'ep:notes/reactions/delete', useClass: ep___notes_reactions_delete.default },
		{ provide: 'ep:notes/renotes', useClass: ep___notes_renotes.default },
		{ provide: 'ep:notes/replies', useClass: ep___notes_replies.default },
		{ provide: 'ep:notes/search-by-tag', useClass: ep___notes_searchByTag.default },
		{ provide: 'ep:notes/search', useClass: ep___notes_search.default },
		{ provide: 'ep:notes/show', useClass: ep___notes_show.default },
		{ provide: 'ep:notes/state', useClass: ep___notes_state.default },
		{ provide: 'ep:notes/thread-muting/create', useClass: ep___notes_threadMuting_create.default },
		{ provide: 'ep:notes/thread-muting/delete', useClass: ep___notes_threadMuting_delete.default },
		{ provide: 'ep:notes/timeline', useClass: ep___notes_timeline.default },
		{ provide: 'ep:notes/translate', useClass: ep___notes_translate.default },
		{ provide: 'ep:notes/unrenote', useClass: ep___notes_unrenote.default },
		{ provide: 'ep:notes/user-list-timeline', useClass: ep___notes_userListTimeline.default },
		{ provide: 'ep:notifications/create', useClass: ep___notifications_create.default },
		{ provide: 'ep:notifications/mark-all-as-read', useClass: ep___notifications_markAllAsRead.default },
		{ provide: 'ep:notifications/read', useClass: ep___notifications_read.default },
		{ provide: 'ep:page-push', useClass: ep___pagePush.default },
		{ provide: 'ep:pages/create', useClass: ep___pages_create.default },
		{ provide: 'ep:pages/delete', useClass: ep___pages_delete.default },
		{ provide: 'ep:pages/featured', useClass: ep___pages_featured.default },
		{ provide: 'ep:pages/like', useClass: ep___pages_like.default },
		{ provide: 'ep:pages/show', useClass: ep___pages_show.default },
		{ provide: 'ep:pages/unlike', useClass: ep___pages_unlike.default },
		{ provide: 'ep:pages/update', useClass: ep___pages_update.default },
		{ provide: 'ep:ping', useClass: ep___ping.default },
		{ provide: 'ep:pinned-users', useClass: ep___pinnedUsers.default },
		{ provide: 'ep:promo/read', useClass: ep___promo_read.default },
		{ provide: 'ep:request-reset-password', useClass: ep___requestResetPassword.default },
		{ provide: 'ep:reset-db', useClass: ep___resetDb.default },
		{ provide: 'ep:reset-password', useClass: ep___resetPassword.default },
		{ provide: 'ep:server-info', useClass: ep___serverInfo.default },
		{ provide: 'ep:stats', useClass: ep___stats.default },
		{ provide: 'ep:sw/register', useClass: ep___sw_register.default },
		{ provide: 'ep:sw/unregister', useClass: ep___sw_unregister.default },
		{ provide: 'ep:test', useClass: ep___test.default },
		{ provide: 'ep:username/available', useClass: ep___username_available.default },
		{ provide: 'ep:users', useClass: ep___users.default },
		{ provide: 'ep:users/clips', useClass: ep___users_clips.default },
		{ provide: 'ep:users/followers', useClass: ep___users_followers.default },
		{ provide: 'ep:users/following', useClass: ep___users_following.default },
		{ provide: 'ep:users/gallery/posts', useClass: ep___users_gallery_posts.default },
		{ provide: 'ep:users/get-frequently-replied-users', useClass: ep___users_getFrequentlyRepliedUsers.default },
		{ provide: 'ep:users/groups/create', useClass: ep___users_groups_create.default },
		{ provide: 'ep:users/groups/delete', useClass: ep___users_groups_delete.default },
		{ provide: 'ep:users/groups/invitations/accept', useClass: ep___users_groups_invitations_accept.default },
		{ provide: 'ep:users/groups/invitations/reject', useClass: ep___users_groups_invitations_reject.default },
		{ provide: 'ep:users/groups/invite', useClass: ep___users_groups_invite.default },
		{ provide: 'ep:users/groups/joined', useClass: ep___users_groups_joined.default },
		{ provide: 'ep:users/groups/leave', useClass: ep___users_groups_leave.default },
		{ provide: 'ep:users/groups/owned', useClass: ep___users_groups_owned.default },
		{ provide: 'ep:users/groups/pull', useClass: ep___users_groups_pull.default },
		{ provide: 'ep:users/groups/show', useClass: ep___users_groups_show.default },
		{ provide: 'ep:users/groups/transfer', useClass: ep___users_groups_transfer.default },
		{ provide: 'ep:users/groups/update', useClass: ep___users_groups_update.default },
		{ provide: 'ep:users/lists/create', useClass: ep___users_lists_create.default },
		{ provide: 'ep:users/lists/delete', useClass: ep___users_lists_delete.default },
		{ provide: 'ep:users/lists/list', useClass: ep___users_lists_list.default },
		{ provide: 'ep:users/lists/pull', useClass: ep___users_lists_pull.default },
		{ provide: 'ep:users/lists/push', useClass: ep___users_lists_push.default },
		{ provide: 'ep:users/lists/show', useClass: ep___users_lists_show.default },
		{ provide: 'ep:users/lists/update', useClass: ep___users_lists_update.default },
		{ provide: 'ep:users/notes', useClass: ep___users_notes.default },
		{ provide: 'ep:users/pages', useClass: ep___users_pages.default },
		{ provide: 'ep:users/reactions', useClass: ep___users_reactions.default },
		{ provide: 'ep:users/recommendation', useClass: ep___users_recommendation.default },
		{ provide: 'ep:users/relation', useClass: ep___users_relation.default },
		{ provide: 'ep:users/report-abuse', useClass: ep___users_reportAbuse.default },
		{ provide: 'ep:users/search-by-username-and-host', useClass: ep___users_searchByUsernameAndHost.default },
		{ provide: 'ep:users/search', useClass: ep___users_search.default },
		{ provide: 'ep:users/show', useClass: ep___users_show.default },
		{ provide: 'ep:users/stats', useClass: ep___users_stats.default },
		{ provide: 'ep:admin/drive-capacity-override', useClass: ep___admin_driveCapOverride.default },
		{ provide: 'ep:fetch-rss', useClass: ep___fetchRss.default },
	],
})
export class EndpointsModule {}
