import { Module } from '@nestjs/common';
import { AbuseUserReports, AccessTokens, Ads, AnnouncementReads, Announcements, AntennaNotes, Antennas, Apps, AttestationChallenges, AuthSessions, Blockings, ChannelFollowings, ChannelNotePinings, Channels, ClipNotes, Clips, DriveFiles, DriveFolders, Emojis, Followings, FollowRequests, GalleryLikes, GalleryPosts, Hashtags, Instances, MessagingMessages, Metas, ModerationLogs, MutedNotes, Mutings, NoteFavorites, NoteReactions, Notes, NoteThreadMutings, NoteUnreads, Notifications, PageLikes, Pages, PasswordResetRequests, Polls, PollVotes, PromoNotes, PromoReads, RegistrationTickets, RegistryItems, Relays, Signins, SwSubscriptions, UsedUsernames, UserGroupInvitations, UserGroupJoinings, UserGroups, UserIps, UserKeypairs, UserListJoinings, UserLists, UserNotePinings, UserPendings, UserProfiles, UserPublickeys, Users, UserSecurityKeys, Webhooks } from '@/models/index.js';

@Module({
	imports: [
	],
	providers: [{
		provide: 'usersRepository',
		useValue: Users,
	}, {
		provide: 'notesRepository',
		useValue: Notes,
	}, {
		provide: 'announcementsRepository',
		useValue: Announcements,
	}, {
		provide: 'announcementReadsRepository',
		useValue: AnnouncementReads,
	}, {
		provide: 'appsRepository',
		useValue: Apps,
	}, {
		provide: 'noteFavoritesRepository',
		useValue: NoteFavorites,
	}, {
		provide: 'noteThreadMutingsRepository',
		useValue: NoteThreadMutings,
	}, {
		provide: 'noteReactionsRepository',
		useValue: NoteReactions,
	}, {
		provide: 'noteUnreadsRepository',
		useValue: NoteUnreads,
	}, {
		provide: 'pollsRepository',
		useValue: Polls,
	}, {
		provide: 'pollVotesRepository',
		useValue: PollVotes,
	}, {
		provide: 'serProfilesRepository',
		useValue: UserProfiles,
	}, {
		provide: 'userKeypairsRepository',
		useValue: UserKeypairs,
	}, {
		provide: 'userPendingsRepository',
		useValue: UserPendings,
	}, {
		provide: 'attestationChallengesRepository',
		useValue: AttestationChallenges,
	}, {
		provide: 'userSecurityKeysRepository',
		useValue: UserSecurityKeys,
	}, {
		provide: 'userPublickeysRepository',
		useValue: UserPublickeys,
	}, {
		provide: 'userListsRepository',
		useValue: UserLists,
	}, {
		provide: 'userListJoiningsRepository',
		useValue: UserListJoinings,
	}, {
		provide: 'userGroupsRepository',
		useValue: UserGroups,
	}, {
		provide: 'userGroupJoiningsRepository',
		useValue: UserGroupJoinings,
	}, {
		provide: 'userGroupInvitationsRepository',
		useValue: UserGroupInvitations,
	}, {
		provide: 'userNotePiningsRepository',
		useValue: UserNotePinings,
	}, {
		provide: 'userIpsRepository',
		useValue: UserIps,
	}, {
		provide: 'usedUsernamesRepository',
		useValue: UsedUsernames,
	}, {
		provide: 'followingsRepository',
		useValue: Followings,
	}, {
		provide: 'followRequestsRepository',
		useValue: FollowRequests,
	}, {
		provide: 'instancesRepository',
		useValue: Instances,
	}, {
		provide: 'emojisRepository',
		useValue: Emojis,
	}, {
		provide: 'driveFilesRepository',
		useValue: DriveFiles,
	}, {
		provide: 'driveFoldersRepository',
		useValue: DriveFolders,
	}, {
		provide: 'notificationsRepository',
		useValue: Notifications,
	}, {
		provide: 'metasRepository',
		useValue: Metas,
	}, {
		provide: 'mutingsRepository',
		useValue: Mutings,
	}, {
		provide: 'blockingsRepository',
		useValue: Blockings,
	}, {
		provide: 'swSubscriptionsRepository',
		useValue: SwSubscriptions,
	}, {
		provide: 'hashtagsRepository',
		useValue: Hashtags,
	}, {
		provide: 'abuseUserReportsRepository',
		useValue: AbuseUserReports,
	}, {
		provide: 'registrationTicketsRepository',
		useValue: RegistrationTickets,
	}, {
		provide: 'authSessionsRepository',
		useValue: AuthSessions,
	}, {
		provide: 'accessTokensRepository',
		useValue: AccessTokens,
	}, {
		provide: 'signinsRepository',
		useValue: Signins,
	}, {
		provide: 'messagingMessagesRepository',
		useValue: MessagingMessages,
	}, {
		provide: 'pagesRepository',
		useValue: Pages,
	}, {
		provide: 'pageLikesRepository',
		useValue: PageLikes,
	}, {
		provide: 'galleryPostsRepository',
		useValue: GalleryPosts,
	}, {
		provide: 'galleryLikesRepository',
		useValue: GalleryLikes,
	}, {
		provide: 'moderationLogsRepository',
		useValue: ModerationLogs,
	}, {
		provide: 'clipsRepository',
		useValue: Clips,
	}, {
		provide: 'clipNotesRepository',
		useValue: ClipNotes,
	}, {
		provide: 'antennasRepository',
		useValue: Antennas,
	}, {
		provide: 'antennaNotesRepository',
		useValue: AntennaNotes,
	}, {
		provide: 'promoNotesRepository',
		useValue: PromoNotes,
	}, {
		provide: 'promoReadsRepository',
		useValue: PromoReads,
	}, {
		provide: 'relaysRepository',
		useValue: Relays,
	}, {
		provide: 'mutedNotesRepository',
		useValue: MutedNotes,
	}, {
		provide: 'channelsRepository',
		useValue: Channels,
	}, {
		provide: 'channelFollowingsRepository',
		useValue: ChannelFollowings,
	}, {
		provide: 'channelNotePiningsRepository',
		useValue: ChannelNotePinings,
	}, {
		provide: 'registryItemsRepository',
		useValue: RegistryItems,
	}, {
		provide: 'webhooksRepository',
		useValue: Webhooks,
	}, {
		provide: 'adsRepository',
		useValue: Ads,
	}, {
		provide: 'passwordResetRequestsRepository',
		useValue: PasswordResetRequests,
	}],
})
export class RepositoryModule {}
