export const katsudoRoleCategories = [
	{
		key: 'position',
		label: '役職系',
		range: '90000〜99990',
		baseOrder: 90000,
		roleNames: ['管理人', 'モデレーター', '貢献者', '信頼できる人'],
	},
	{
		key: 'recruit',
		label: '募集・依頼系',
		range: '80000〜89990',
		baseOrder: 80000,
		roleNames: ['イラスト依頼受付中', 'グループメンバー募集中'],
	},
	{
		key: 'bot',
		label: 'bot系',
		range: '70000〜79990',
		baseOrder: 70000,
		roleNames: ['管理系bot'],
	},
	{
		key: 'restriction',
		label: '制限系',
		range: '60000〜69990',
		baseOrder: 60000,
		roleNames: ['ローカルできないよ', 'ホームでやろうね', 'グループの規約違反', '荒らし行為'],
	},
	{
		key: 'activity',
		label: '活動系',
		range: '50000〜59990',
		baseOrder: 50000,
		roleNames: ['配信者', '絵チャ配信者', 'ゲーム実況者', 'YouTuber', 'ITuber', '歌い手', 'ボカロP', 'UTAU音源制作者', '絵師', 'ロゴ師', '写真家', '声優'],
	},
        {
                key: 'rank',
                label: '活動称号系',
                range: '20000〜29990',
                baseOrder: 20000,
                roleNames: [
                        'かつ廃見習い',
                        'かつ廃三級',
                        'かつ廃二級',
                        'かつ廃一級',
                        'かつ廃一段',
                ],
        },
	{
		key: 'fan',
		label: 'ファンロール系',
		range: '40000〜49990',
		baseOrder: 40000,
		roleNames: ['かつどうおばけ', 'かつどる親衛隊', 'タコス猫教信者', 'タコス猫教 教祖', 'くらげ民', 'しーうお隊'],
	},
	{
		key: 'group',
		label: 'グループ系',
		range: '30000〜39990',
		baseOrder: 30000,
		roleNames: ['グループアカウント', '小説部', 'からめん'],
	},
	{
		key: 'fun',
		label: 'ネタ・称号系',
		range: '10000〜19990',
		baseOrder: 10000,
		roleNames: ['永住します', 'フラグ建築士', '暇人さん', 'まさかの知り合い'],
	},
	{
		key: 'uncategorized',
		label: '未分類',
		range: '番号帯未定',
		baseOrder: 0,
		roleNames: [],
	},
] as const;
