export const katsudoRoleCategories = [
	{
		key: 'position',
		label: '役職系',
		range: '9000〜9999',
		baseOrder: 9000,
		roleNames: ['管理人', 'モデレーター', '貢献者', '信頼できる人'],
	},
	{
		key: 'recruit',
		label: '募集・依頼系',
		range: '8000〜8999',
		baseOrder: 8000,
		roleNames: ['イラスト依頼受付中', 'グループメンバー募集中'],
	},
	{
		key: 'bot',
		label: 'bot系',
		range: '7000〜7999',
		baseOrder: 7000,
		roleNames: ['管理系bot'],
	},
	{
		key: 'restriction',
		label: '制限系',
		range: '6000〜6999',
		baseOrder: 6000,
		roleNames: ['ローカルできないよ', 'ホームでやろうね', 'グループの規約違反', '荒らし行為'],
	},
	{
		key: 'activity',
		label: '活動系',
		range: '5000〜5999',
		baseOrder: 5000,
		roleNames: ['配信者', '絵チャ配信者', 'ゲーム実況者', 'YouTuber', 'ITuber', '歌い手', 'ボカロP', 'UTAU音源制作者', '絵師', 'ロゴ師', '写真家', '声優'],
	},
	{
		key: 'fan',
		label: 'ファンロール系',
		range: '4000〜4999',
		baseOrder: 4000,
		roleNames: ['かつどうおばけ', 'かつどる親衛隊', 'タコス猫教信者', 'タコス猫教 教祖', 'くらげ民', 'しーうお隊'],
	},
	{
		key: 'group',
		label: 'グループ系',
		range: '3000〜3999',
		baseOrder: 3000,
		roleNames: ['グループアカウント', '小説部', 'からめん'],
	},
	{
		key: 'fun',
		label: 'ネタ・称号系',
		range: '1000〜1999',
		baseOrder: 1000,
		roleNames: ['永住します', 'フラグ建築士', '暇人さん', 'まさかの知り合い'],
	},
	{
		key: 'uncategorized',
		label: '未分類',
		range: '番号帯未定',
		baseOrder: 0,
		roleNames: [],
	},
] as const;
