import type { entities } from 'misskey-js'

export const userDetailed = {
	id: 'someuserid',
	username: 'miskist',
	host: 'misskey-hub.net',
	name: 'Misskey User',
	onlineStatus: 'unknown',
	avatarUrl: 'https://github.com/misskey-dev/misskey/blob/master/packages/frontend/assets/about-icon.png?raw=true',
	avatarBlurhash: 'eQFRshof5NWBRi},juayfPju53WB?0ofs;s*a{ofjuay^SoMEJR%ay',
	emojis: [],
	bannerBlurhash: 'eQA^IW^-MH8w9tE8I=S^o{$*R4RikXtSxutRozjEnNR.RQadoyozog',
	bannerColor: '#000000',
	bannerUrl: 'https://github.com/misskey-dev/misskey/blob/master/packages/frontend/assets/fedi.jpg?raw=true',
	birthday: '2014-06-20',
	createdAt: '2016-12-28T22:49:51.000Z',
	description: 'I am a cool user!',
	ffVisibility: 'public',
	fields: [
		{
			name: 'Website',
			value: 'https://misskey-hub.net',
		},
	],
	followersCount: 1024,
	followingCount: 16,
	hasPendingFollowRequestFromYou: false,
	hasPendingFollowRequestToYou: false,
	isAdmin: false,
	isBlocked: false,
	isBlocking: false,
	isBot: false,
	isCat: false,
	isFollowed: false,
	isFollowing: false,
	isLocked: false,
	isModerator: false,
	isMuted: false,
	isSilenced: false,
	isSuspended: false,
	lang: 'en',
	location: 'Fediverse',
	notesCount: 65536,
	pinnedNoteIds: [],
	pinnedNotes: [],
	pinnedPage: null,
	pinnedPageId: null,
	publicReactions: false,
	securityKeys: false,
	twoFactorEnabled: false,
	updatedAt: null,
	uri: null,
	url: null,
} satisfies entities.UserDetailed
