
/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// This file was automatically generated by create-search-index.
// Do not edit this file.

import { i18n } from '@/i18n.js';

export type SearchIndexItem = {
	id: string;
	path?: string;
	label: string;
	keywords: string[];
	icon?: string;
	children?: SearchIndexItem[];
};

export const searchIndexes:SearchIndexItem[] = [
	{
		id: 'lkiKsD6A9',
		children: [
			{
				id: '4WPlJ524l',
				label: i18n.ts.uiLanguage,
				keywords: ['language'],
			},
			{
				id: 'gdnOIq6gV',
				label: i18n.ts.overridedDeviceKind,
				keywords: ['device', 'type', 'kind', 'smartphone', 'tablet', 'desktop'],
			},
			{
				id: '7I09lqpHF',
				label: i18n.ts.showFixedPostForm,
				keywords: ['post', 'form', 'timeline'],
			},
			{
				id: '3mSEIzyAn',
				label: i18n.ts.showFixedPostFormInChannel,
				keywords: ['post', 'form', 'timeline', 'channel'],
			},
			{
				id: 'twBuPNC7r',
				label: i18n.ts.pinnedList,
				keywords: ['pinned', 'list'],
			},
			{
				id: 'hLZFPY700',
				children: [
					{
						id: 'vJqTLkoGN',
						label: i18n.ts.collapseRenotes,
						keywords: ['renote', i18n.ts.collapseRenotesDescription],
					},
					{
						id: '4cggLmqKJ',
						label: i18n.ts.showNoteActionsOnlyHover,
						keywords: ['hover', 'show', 'footer', 'action'],
					},
					{
						id: 'i1ndjCPQj',
						label: i18n.ts.showClipButtonInNoteFooter,
						keywords: ['footer', 'action', 'clip', 'show'],
					},
					{
						id: 'kiklmNkV',
						label: i18n.ts.enableAdvancedMfm,
						keywords: ['mfm', 'enable', 'show', 'advanced'],
					},
					{
						id: 'x68Ox4Sh6',
						label: i18n.ts.enableAnimatedMfm,
						keywords: ['mfm', 'enable', 'show', 'animated'],
					},
					{
						id: 'B0Jy4i5oa',
						label: i18n.ts.enableQuickAddMfmFunction,
						keywords: ['mfm', 'enable', 'show', 'advanced', 'picker', 'form', 'function', 'fn'],
					},
					{
						id: '1N0q2HWTs',
						label: i18n.ts.showReactionsCount,
						keywords: ['reaction', 'count', 'show'],
					},
					{
						id: 'ieWwnnJWn',
						label: i18n.ts.showGapBetweenNotesInTimeline,
						keywords: ['note', 'timeline', 'gap'],
					},
					{
						id: 'mWq0ltyPE',
						label: i18n.ts.loadRawImages,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'quality', 'raw', 'attachment'],
					},
					{
						id: 'lXddCBaxo',
						label: i18n.ts.reactionsDisplaySize,
						keywords: ['reaction', 'size', 'scale', 'display'],
					},
					{
						id: 'E8W5lEQ7k',
						label: i18n.ts.limitWidthOfReaction,
						keywords: ['reaction', 'size', 'scale', 'display', 'width', 'limit'],
					},
					{
						id: 'AP0K0zIFZ',
						label: i18n.ts.instanceTicker,
						keywords: ['ticker', 'information', 'label', 'instance', 'server', 'host', 'federation'],
					},
					{
						id: 'zONwrNCVk',
						label: i18n.ts.displayOfSensitiveMedia,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'nsfw', 'sensitive', 'display', 'show', 'hide', 'visibility'],
					},
					{
						id: '9cdXUsNPS',
						label: i18n.ts.mediaListWithOneImageAppearance,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'list', 'size', 'height'],
					},
				],
				label: i18n.ts.displayOfNote,
				keywords: ['note', 'display'],
			},
			{
				id: 'rj7TUPwRw',
				children: [
					{
						id: '6LpEmuv0Q',
						label: i18n.ts.useGroupedNotifications,
						keywords: ['group'],
					},
					{
						id: 'jOlwSaPaw',
						label: i18n.ts.position,
						keywords: ['position'],
					},
					{
						id: '7XcjNgCmm',
						label: i18n.ts.stackAxis,
						keywords: ['stack', 'axis', 'direction'],
					},
				],
				label: i18n.ts.notificationDisplay,
				keywords: ['notification', 'display'],
			},
			{
				id: 'ACC9AWbOk',
				children: [
					{
						id: 'y653DAEsf',
						label: i18n.ts.reduceUiAnimation,
						keywords: ['animation', 'motion', 'reduce'],
					},
					{
						id: 'ayoWd2b6Z',
						label: i18n.ts.useBlurEffect,
						keywords: ['blur'],
					},
					{
						id: 'uYmriYfT1',
						label: i18n.ts.useBlurEffectForModal,
						keywords: ['blur', 'modal'],
					},
					{
						id: '5ozJxjj1c',
						label: i18n.ts.disableShowingAnimatedImages,
						keywords: ['disable', 'animation', 'image', 'photo', 'picture', 'media', 'thumbnail', 'gif'],
					},
					{
						id: 'tUI7a0JWj',
						label: i18n.ts.highlightSensitiveMedia,
						keywords: ['highlight', 'sensitive', 'nsfw', 'image', 'photo', 'picture', 'media', 'thumbnail'],
					},
					{
						id: 'bfHGKlGNB',
						label: i18n.ts.squareAvatars,
						keywords: ['avatar', 'icon', 'square'],
					},
					{
						id: 'sHiN9kH7D',
						label: i18n.ts.showAvatarDecorations,
						keywords: ['avatar', 'icon', 'decoration', 'show'],
					},
					{
						id: 'gL6fTIHyP',
						label: i18n.ts.useSystemFont,
						keywords: ['font', 'system', 'native'],
					},
					{
						id: 'xDLa6kVQF',
						label: i18n.ts.forceShowAds,
						keywords: ['ad', 'show'],
					},
					{
						id: 'p7GQhg0Y9',
						label: i18n.ts.seasonalScreenEffect,
						keywords: ['effect', 'show'],
					},
					{
						id: 'fhmvNkgS7',
						label: i18n.ts.useNativeUIForVideoAudioPlayer,
						keywords: ['native', 'system', 'video', 'audio', 'player', 'media'],
					},
					{
						id: '4VVCvIuPm',
						label: i18n.ts.menuStyle,
						keywords: ['menu', 'style', 'popup', 'drawer'],
					},
					{
						id: 'IXadN8TM',
						label: i18n.ts.emojiStyle,
						keywords: ['emoji', 'style', 'native', 'system', 'fluent', 'twemoji'],
					},
					{
						id: '5vq6CRAi6',
						label: i18n.ts.fontSize,
						keywords: ['font', 'size'],
					},
				],
				label: i18n.ts.appearance,
				keywords: ['appearance'],
			},
			{
				id: 'bEhm5hQNT',
				children: [
					{
						id: '6HHClKdX5',
						label: i18n.ts.openImageInNewTab,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'new', 'tab'],
					},
					{
						id: 'uauZuKyrN',
						label: i18n.ts.useReactionPickerForContextMenu,
						keywords: ['reaction', 'picker', 'contextmenu', 'open'],
					},
					{
						id: 'bApEtrnbQ',
						label: i18n.ts.enableInfiniteScroll,
						keywords: ['load', 'auto', 'more'],
					},
					{
						id: '2ZIJYETQZ',
						label: i18n.ts.keepScreenOn,
						keywords: ['keep', 'screen', 'display', 'on'],
					},
					{
						id: 'ERnduxmpk',
						label: i18n.ts.disableStreamingTimeline,
						keywords: ['disable', 'streaming', 'timeline'],
					},
					{
						id: 'eW59NN3mh',
						label: i18n.ts.enableHorizontalSwipe,
						keywords: ['swipe', 'horizontal', 'tab'],
					},
					{
						id: 'ruPid3INR',
						label: i18n.ts.alwaysConfirmFollow,
						keywords: ['follow', 'confirm', 'always'],
					},
					{
						id: 'oxWIfLvAb',
						label: i18n.ts.confirmWhenRevealingSensitiveMedia,
						keywords: ['sensitive', 'nsfw', 'media', 'image', 'photo', 'picture', 'attachment', 'confirm'],
					},
					{
						id: 'gBJ7T4b2K',
						label: i18n.ts.confirmOnReact,
						keywords: ['reaction', 'confirm'],
					},
					{
						id: '16hCison3',
						label: i18n.ts.whenServerDisconnected,
						keywords: ['server', 'disconnect', 'reconnect', 'reload', 'streaming'],
					},
					{
						id: 'x6SxTt3LO',
						label: i18n.ts._contextMenu.title,
						keywords: ['contextmenu', 'system', 'native'],
					},
					{
						id: 'EZrtSg5OI',
						label: i18n.ts.numberOfPageCache,
						keywords: ['cache', 'page'],
					},
					{
						id: '4DlMuvw4O',
						label: i18n.ts.dataSaver,
						keywords: ['datasaver'],
					},
				],
				label: i18n.ts.behavior,
				keywords: ['behavior'],
			},
		],
		label: i18n.ts.general,
		keywords: ['general'],
		icon: 'ti ti-adjustments',
	},
	{
		id: '3P5SEWR1V',
		label: i18n.ts._profile.name,
		keywords: ['name'],
	},
	{
		id: '6aLDUSc29',
		label: i18n.ts._profile.description,
		keywords: ['description', 'bio'],
	},
	{
		id: 'v6Kb9mcQm',
		label: i18n.ts.birthday,
		keywords: ['birthday', 'birthdate', 'age'],
	},
	{
		id: 'wQdjXX2EP',
		label: i18n.ts.language,
		keywords: ['language', 'locale'],
	},
	{
		id: 'x3ycuUD3Z',
		label: i18n.ts._profile.metadataEdit,
		keywords: ['metadata'],
	},
	{
		id: '2UiyyvRM3',
		label: i18n.ts._profile.followedMessage,
		keywords: ['follow', 'message', i18n.ts._profile.followedMessageDescription],
	},
	{
		id: 'HDa1YkPR',
		label: i18n.ts.reactionAcceptance,
		keywords: ['reaction'],
	},
	{
		id: '8zWWmVNIj',
		children: [
			{
				id: 'fuNNuX4Qs',
				label: i18n.ts.flagAsCat,
				keywords: ['cat', i18n.ts.flagAsCatDescription],
			},
			{
				id: 'AP0K0zIFZ',
				label: i18n.ts.instanceTicker,
				keywords: ['ticker', 'information', 'label', 'instance', 'server', 'host', 'federation'],
			},
		],
		label: i18n.ts.advancedSettings,
		keywords: [],
	},
	{
		id: '85HeLKpoq',
		label: i18n.ts.autoAcceptFollowed,
		keywords: ['follow', 'auto', 'accept'],
	},
	{
		id: 'zTZP66QHY',
		label: i18n.ts.makeReactionsPublic,
		keywords: ['reaction', 'public', i18n.ts.makeReactionsPublicDescription],
	},
	{
		id: 'kDLSN7bfc',
		label: i18n.ts.followingVisibility,
		keywords: ['following', 'visibility'],
	},
	{
		id: 'CAArBJ4cp',
		label: i18n.ts.followersVisibility,
		keywords: ['follower', 'visibility'],
	},
	{
		id: 'eoe8L1ZlA',
		label: i18n.ts.hideOnlineStatus,
		keywords: ['online', 'status', i18n.ts.hideOnlineStatusDescription],
	},
	{
		id: 'seZrrw59b',
		label: i18n.ts.noCrawle,
		keywords: ['crawle', 'index', 'search', i18n.ts.noCrawleDescription],
	},
	{
		id: 'AdDcoGIcU',
		label: i18n.ts.preventAiLearning,
		keywords: ['crawle', 'ai', i18n.ts.preventAiLearningDescription],
	},
	{
		id: 'x8f9vXsii',
		label: i18n.ts.makeExplorable,
		keywords: ['explore', i18n.ts.makeExplorableDescription],
	},
	{
		id: 'bftvzhrY4',
		children: [
			{
				id: 'B2RwMdOhi',
				label: i18n.ts._accountSettings.requireSigninToViewContents,
				keywords: ['login', 'signin', i18n.ts._accountSettings.requireSigninToViewContentsDescription1, i18n.ts._accountSettings.requireSigninToViewContentsDescription2, i18n.ts._accountSettings.requireSigninToViewContentsDescription3],
			},
			{
				id: '6wIRtpKLT',
				label: i18n.ts._accountSettings.makeNotesFollowersOnlyBefore,
				keywords: ['follower', i18n.ts._accountSettings.makeNotesFollowersOnlyBeforeDescription],
			},
			{
				id: 'uK0LXZ9QL',
				label: i18n.ts._accountSettings.makeNotesHiddenBefore,
				keywords: ['hidden', i18n.ts._accountSettings.makeNotesHiddenBeforeDescription],
			},
		],
		label: i18n.ts.lockdown,
		keywords: ['lockdown'],
	},
	{
		id: 'oIJtwMQR1',
		label: i18n.ts.rememberNoteVisibility,
		keywords: ['remember', 'keep', 'note', 'visibility'],
	},
	{
		id: 'yFBbKl1Qy',
		label: i18n.ts.defaultNoteVisibility,
		keywords: ['default', 'note', 'visibility'],
	},
	{
		id: 't2ji5R82J',
		label: i18n.ts.keepCw,
		keywords: ['remember', 'keep', 'note', 'cw'],
	},
	{
		id: '1yWthuQGm',
		label: i18n.ts.showMutedWord,
		keywords: ['show'],
	},
	{
		id: 'gmw2pWwJA',
		label: i18n.ts.hardWordMute,
		keywords: ['note', 'word', 'hard', 'mute', 'hide'],
	},
	{
		id: 'tpSclMQgy',
		label: i18n.ts.instanceMute,
		keywords: ['note', 'server', 'instance', 'host', 'federation', 'mute', 'hide'],
	},
	{
		id: 'rTmclo0x',
		label: `${i18n.ts.mutedUsers} (${ i18n.ts.renote })`,
		keywords: ['renote', 'mute', 'hide', 'user'],
	},
	{
		id: 'pq69uSb0G',
		label: i18n.ts.mutedUsers,
		keywords: ['note', 'mute', 'hide', 'user'],
	},
] as const;

export type SearchIndex = typeof searchIndexes;
