
/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// This file was automatically generated by create-search-index.
// Do not edit this file.

import { i18n } from '@/i18n.js';

export const searchIndexes = [
	{
		filePath: 'src/pages/settings/profile.vue',
		usage: [
			{
				staticProps: {
					markerId: '4mWPWOqkN',
				},
				bindProps: {},
			},
			{
				staticProps: {
					markerId: 'gw1zundQ3',
				},
				bindProps: {},
			},
		],
	},
	{
		filePath: 'src/pages/settings/privacy.vue',
		usage: [
			{
				staticProps: {
					icon: 'ti ti-lock-open',
					markerId: 'ssTCH2oBL',
				},
				bindProps: {
					locationLabel: [i18n.ts.privacy, i18n.ts.makeFollowManuallyApprove],
					keywords: ['follow', 'lock', i18n.ts.lockedAccountInfo],
				},
			},
		],
	},
	{
		filePath: 'src/pages/settings/mute-block.vue',
		usage: [
			{
				staticProps: {
					icon: 'ti ti-ban',
					markerId: 'CVhDOYgMv',
				},
				bindProps: {
					locationLabel: [i18n.ts.muteAndBlock],
					keywords: ['mute', i18n.ts.wordMute],
					children: [
						'kcHPXo5ZV',
					],
				},
			},
			{
				staticProps: {
					icon: 'ti ti-ban',
					markerId: 'kcHPXo5ZV',
				},
				bindProps: {
					locationLabel: [i18n.ts.muteAndBlock, i18n.ts.wordMute],
					keywords: ['showMutedWord', i18n.ts.showMutedWord],
				},
			},
		],
	},
] as const;

export type AnalysisResults = typeof searchIndexes;
export type ComponentUsageInfo = AnalysisResults[number]['usage'][number];
