
/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// This file was automatically generated by create-search-index.
// Do not edit this file.

import { i18n } from '@/i18n.js';

export type SearchIndexItem = {
	id: string;
	path?: string;
	label: string;
	keywords: string[];
	icon?: string;
	children?: SearchIndexItem[];
};

export const searchIndexes:SearchIndexItem[] = [
	{
		id: 'marker-ivoxldn2',
		children: [
			{
				id: 'marker-442hcgtm',
				label: i18n.ts._profile.name,
				keywords: ['name'],
			},
			{
				id: 'marker-rv9gdc0i',
				label: i18n.ts._profile.description,
				keywords: ['description', 'bio'],
			},
			{
				id: 'marker-m12hb2cg',
				label: i18n.ts.location,
				keywords: ['location', 'locale'],
			},
			{
				id: 'marker-8ghv5rt5',
				label: i18n.ts.birthday,
				keywords: ['birthday', 'birthdate', 'age'],
			},
			{
				id: 'marker-pgvmorvh',
				label: i18n.ts.language,
				keywords: ['language', 'locale'],
			},
			{
				id: 'marker-x2k1chpn',
				label: i18n.ts._profile.metadataEdit,
				keywords: ['metadata'],
			},
			{
				id: 'marker-jjutta5s',
				label: i18n.ts._profile.followedMessage,
				keywords: ['follow', 'message', i18n.ts._profile.followedMessageDescription],
			},
			{
				id: 'marker-pmexhj89',
				label: i18n.ts.reactionAcceptance,
				keywords: ['reaction'],
			},
			{
				id: 'marker-ycrvsaf6',
				children: [
					{
						id: 'marker-oigaag5u',
						label: i18n.ts.flagAsCat,
						keywords: ['cat', i18n.ts.flagAsCatDescription],
					},
					{
						id: 'marker-8e5my3jw',
						label: i18n.ts.flagAsBot,
						keywords: ['bot', i18n.ts.flagAsBotDescription],
					},
				],
				label: i18n.ts.advancedSettings,
				keywords: [],
			},
		],
		label: i18n.ts.profile,
		keywords: ['profile'],
		path: '/settings/profile',
		icon: 'ti ti-user',
	},
	{
		id: 'marker-qkmo5xt7',
		children: [
			{
				id: 'marker-gq65ed46',
				label: i18n.ts.makeFollowManuallyApprove,
				keywords: ['follow', 'lock', i18n.ts.lockedAccountInfo],
			},
			{
				id: 'marker-us4p761g',
				label: i18n.ts.autoAcceptFollowed,
				keywords: ['follow', 'auto', 'accept'],
			},
			{
				id: 'marker-ltdqnojh',
				label: i18n.ts.makeReactionsPublic,
				keywords: ['reaction', 'public', i18n.ts.makeReactionsPublicDescription],
			},
			{
				id: 'marker-28jtlr19',
				label: i18n.ts.followingVisibility,
				keywords: ['following', 'visibility'],
			},
			{
				id: 'marker-x8p8jntc',
				label: i18n.ts.followersVisibility,
				keywords: ['follower', 'visibility'],
			},
			{
				id: 'marker-wl1av375',
				label: i18n.ts.hideOnlineStatus,
				keywords: ['online', 'status', i18n.ts.hideOnlineStatusDescription],
			},
			{
				id: 'marker-o9mx5epn',
				label: i18n.ts.noCrawle,
				keywords: ['crawle', 'index', 'search', i18n.ts.noCrawleDescription],
			},
			{
				id: 'marker-nlrfi880',
				label: i18n.ts.preventAiLearning,
				keywords: ['crawle', 'ai', i18n.ts.preventAiLearningDescription],
			},
			{
				id: 'marker-meuqilul',
				label: i18n.ts.makeExplorable,
				keywords: ['explore', i18n.ts.makeExplorableDescription],
			},
			{
				id: 'marker-xh8dhnmy',
				children: [
					{
						id: 'marker-d8j5spte',
						label: i18n.ts._accountSettings.requireSigninToViewContents,
						keywords: ['login', 'signin', i18n.ts._accountSettings.requireSigninToViewContentsDescription1, i18n.ts._accountSettings.requireSigninToViewContentsDescription2, i18n.ts._accountSettings.requireSigninToViewContentsDescription3],
					},
					{
						id: 'marker-jqrc6mwj',
						label: i18n.ts._accountSettings.makeNotesFollowersOnlyBefore,
						keywords: ['follower', i18n.ts._accountSettings.makeNotesFollowersOnlyBeforeDescription],
					},
					{
						id: 'marker-ixe02l4z',
						label: i18n.ts._accountSettings.makeNotesHiddenBefore,
						keywords: ['hidden', i18n.ts._accountSettings.makeNotesHiddenBeforeDescription],
					},
				],
				label: i18n.ts.lockdown,
				keywords: ['lockdown'],
			},
			{
				id: 'marker-jnzn6ufj',
				label: i18n.ts.rememberNoteVisibility,
				keywords: ['remember', 'keep', 'note', 'visibility'],
			},
			{
				id: 'marker-3ckk29gw',
				label: i18n.ts.defaultNoteVisibility,
				keywords: ['default', 'note', 'visibility'],
			},
			{
				id: 'marker-g2rd6clc',
				label: i18n.ts.keepCw,
				keywords: ['remember', 'keep', 'note', 'cw'],
			},
		],
		label: i18n.ts.privacy,
		keywords: ['privacy'],
		path: '/settings/privacy',
		icon: 'ti ti-lock-open',
	},
	{
		id: 'marker-dmj8mric',
		children: [
			{
				id: 'marker-rlomnwy4',
				children: [
					{
						id: 'marker-03maf29t',
						label: i18n.ts.showMutedWord,
						keywords: ['show'],
					},
				],
				label: i18n.ts.wordMute,
				keywords: ['note', 'word', 'soft', 'mute', 'hide'],
			},
			{
				id: 'marker-5kzrz4t5',
				label: i18n.ts.hardWordMute,
				keywords: ['note', 'word', 'hard', 'mute', 'hide'],
			},
			{
				id: 'marker-ptyw2prf',
				label: i18n.ts.instanceMute,
				keywords: ['note', 'server', 'instance', 'host', 'federation', 'mute', 'hide'],
			},
			{
				id: 'marker-epiezv85',
				label: `${i18n.ts.mutedUsers} (${ i18n.ts.renote })`,
				keywords: ['renote', 'mute', 'hide', 'user'],
			},
			{
				id: 'marker-ilputfis',
				label: i18n.ts.mutedUsers,
				keywords: ['note', 'mute', 'hide', 'user'],
			},
			{
				id: 'marker-304lg4wb',
				label: i18n.ts.blockedUsers,
				keywords: ['block', 'user'],
			},
		],
		label: i18n.ts.muteAndBlock,
		keywords: ['mute', 'block'],
		path: '/settings/mute-block',
		icon: 'ti ti-ban',
	},
	{
		id: 'marker-f6l3ctlv',
		children: [
			{
				id: 'marker-rm16co08',
				label: i18n.ts.uiLanguage,
				keywords: ['language'],
			},
			{
				id: 'marker-ovxxndfu',
				label: i18n.ts.overridedDeviceKind,
				keywords: ['device', 'type', 'kind', 'smartphone', 'tablet', 'desktop'],
			},
			{
				id: 'marker-k3kz2rjt',
				label: i18n.ts.showFixedPostForm,
				keywords: ['post', 'form', 'timeline'],
			},
			{
				id: 'marker-2o43q70p',
				label: i18n.ts.showFixedPostFormInChannel,
				keywords: ['post', 'form', 'timeline', 'channel'],
			},
			{
				id: 'marker-x65x1cua',
				label: i18n.ts.pinnedList,
				keywords: ['pinned', 'list'],
			},
			{
				id: 'marker-bd2jol5x',
				children: [
					{
						id: 'marker-t1kgtukj',
						label: i18n.ts.collapseRenotes,
						keywords: ['renote', i18n.ts.collapseRenotesDescription],
					},
					{
						id: 'marker-ggf1jcz4',
						label: i18n.ts.showNoteActionsOnlyHover,
						keywords: ['hover', 'show', 'footer', 'action'],
					},
					{
						id: 'marker-vtkhzc0l',
						label: i18n.ts.showClipButtonInNoteFooter,
						keywords: ['footer', 'action', 'clip', 'show'],
					},
					{
						id: 'marker-nfqqk7xd',
						label: i18n.ts.enableAdvancedMfm,
						keywords: ['mfm', 'enable', 'show', 'advanced'],
					},
					{
						id: 'marker-o4lbfl0j',
						label: i18n.ts.enableAnimatedMfm,
						keywords: ['mfm', 'enable', 'show', 'animated'],
					},
					{
						id: 'marker-08pdc0i5',
						label: i18n.ts.enableQuickAddMfmFunction,
						keywords: ['mfm', 'enable', 'show', 'advanced', 'picker', 'form', 'function', 'fn'],
					},
					{
						id: 'marker-ci1v1ju0',
						label: i18n.ts.showReactionsCount,
						keywords: ['reaction', 'count', 'show'],
					},
					{
						id: 'marker-vq1li3y5',
						label: i18n.ts.showGapBetweenNotesInTimeline,
						keywords: ['note', 'timeline', 'gap'],
					},
					{
						id: 'marker-4zzmm7rh',
						label: i18n.ts.loadRawImages,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'quality', 'raw', 'attachment'],
					},
					{
						id: 'marker-zdl3a4x4',
						label: i18n.ts.reactionsDisplaySize,
						keywords: ['reaction', 'size', 'scale', 'display'],
					},
					{
						id: 'marker-lf78qj0l',
						label: i18n.ts.limitWidthOfReaction,
						keywords: ['reaction', 'size', 'scale', 'display', 'width', 'limit'],
					},
					{
						id: 'marker-1g3tuirr',
						label: i18n.ts.instanceTicker,
						keywords: ['ticker', 'information', 'label', 'instance', 'server', 'host', 'federation'],
					},
					{
						id: 'marker-bc0by80n',
						label: i18n.ts.displayOfSensitiveMedia,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'nsfw', 'sensitive', 'display', 'show', 'hide', 'visibility'],
					},
					{
						id: 'marker-050keh4u',
						label: i18n.ts.mediaListWithOneImageAppearance,
						keywords: ['attachment', 'image', 'photo', 'picture', 'media', 'thumbnail', 'list', 'size', 'height'],
					},
				],
				label: i18n.ts.displayOfNote,
				keywords: ['note', 'display'],
			},
			{
				id: 'marker-ontmcscb',
				children: [
					{
						id: 'marker-jtc2j2vk',
						label: i18n.ts.useGroupedNotifications,
						keywords: ['group'],
					},
					{
						id: 'marker-2c0dfum1',
						label: i18n.ts.position,
						keywords: ['position'],
					},
					{
						id: 'marker-8cpow4bx',
						label: i18n.ts.stackAxis,
						keywords: ['stack', 'axis', 'direction'],
					},
				],
				label: i18n.ts.notificationDisplay,
				keywords: ['notification', 'display'],
			},
			{
				id: 'marker-ll2x7yjf',
				children: [
					{
						id: 'marker-q6spj6dn',
						label: i18n.ts.reduceUiAnimation,
						keywords: ['animation', 'motion', 'reduce'],
					},
					{
						id: 'marker-kpw3mmoq',
						label: i18n.ts.useBlurEffect,
						keywords: ['blur'],
					},
					{
						id: 'marker-3x3evqye',
						label: i18n.ts.useBlurEffectForModal,
						keywords: ['blur', 'modal'],
					},
					{
						id: 'marker-8xmqhbab',
						label: i18n.ts.disableShowingAnimatedImages,
						keywords: ['disable', 'animation', 'image', 'photo', 'picture', 'media', 'thumbnail', 'gif'],
					},
					{
						id: 'marker-8pkps5p8',
						label: i18n.ts.highlightSensitiveMedia,
						keywords: ['highlight', 'sensitive', 'nsfw', 'image', 'photo', 'picture', 'media', 'thumbnail'],
					},
					{
						id: 'marker-t9guemea',
						label: i18n.ts.squareAvatars,
						keywords: ['avatar', 'icon', 'square'],
					},
					{
						id: 'marker-eb58wnac',
						label: i18n.ts.showAvatarDecorations,
						keywords: ['avatar', 'icon', 'decoration', 'show'],
					},
					{
						id: 'marker-5s4pr4hg',
						label: i18n.ts.useSystemFont,
						keywords: ['font', 'system', 'native'],
					},
					{
						id: 'marker-m94oss9b',
						label: i18n.ts.forceShowAds,
						keywords: ['ad', 'show'],
					},
					{
						id: 'marker-zy7zggt9',
						label: i18n.ts.seasonalScreenEffect,
						keywords: ['effect', 'show'],
					},
					{
						id: 'marker-4dqzhhx5',
						label: i18n.ts.useNativeUIForVideoAudioPlayer,
						keywords: ['native', 'system', 'video', 'audio', 'player', 'media'],
					},
					{
						id: 'marker-89ux5qm5',
						label: i18n.ts.menuStyle,
						keywords: ['menu', 'style', 'popup', 'drawer'],
					},
					{
						id: 'marker-6k38wplg',
						label: i18n.ts.emojiStyle,
						keywords: ['emoji', 'style', 'native', 'system', 'fluent', 'twemoji'],
					},
					{
						id: 'marker-ux9fnd1o',
						label: i18n.ts.fontSize,
						keywords: ['font', 'size'],
					},
				],
				label: i18n.ts.appearance,
				keywords: ['appearance'],
			},
			{
				id: 'marker-54qde4dz',
				children: [
					{
						id: 'marker-w266ia02',
						label: i18n.ts.openImageInNewTab,
						keywords: ['image', 'photo', 'picture', 'media', 'thumbnail', 'new', 'tab'],
					},
					{
						id: 'marker-qga4vg3h',
						label: i18n.ts.useReactionPickerForContextMenu,
						keywords: ['reaction', 'picker', 'contextmenu', 'open'],
					},
					{
						id: 'marker-034surqc',
						label: i18n.ts.enableInfiniteScroll,
						keywords: ['load', 'auto', 'more'],
					},
					{
						id: 'marker-hpxyuoft',
						label: i18n.ts.keepScreenOn,
						keywords: ['keep', 'screen', 'display', 'on'],
					},
					{
						id: 'marker-hqux8ljb',
						label: i18n.ts.disableStreamingTimeline,
						keywords: ['disable', 'streaming', 'timeline'],
					},
					{
						id: 'marker-9k3fmkjq',
						label: i18n.ts.enableHorizontalSwipe,
						keywords: ['swipe', 'horizontal', 'tab'],
					},
					{
						id: 'marker-0f43qpk3',
						label: i18n.ts.alwaysConfirmFollow,
						keywords: ['follow', 'confirm', 'always'],
					},
					{
						id: 'marker-2s2ry7hk',
						label: i18n.ts.confirmWhenRevealingSensitiveMedia,
						keywords: ['sensitive', 'nsfw', 'media', 'image', 'photo', 'picture', 'attachment', 'confirm'],
					},
					{
						id: 'marker-8xiglms2',
						label: i18n.ts.confirmOnReact,
						keywords: ['reaction', 'confirm'],
					},
					{
						id: 'marker-17gnrcdd',
						label: i18n.ts.whenServerDisconnected,
						keywords: ['server', 'disconnect', 'reconnect', 'reload', 'streaming'],
					},
					{
						id: 'marker-8kzrvf60',
						label: i18n.ts._contextMenu.title,
						keywords: ['contextmenu', 'system', 'native'],
					},
					{
						id: 'marker-rtxgjbdb',
						label: i18n.ts.numberOfPageCache,
						keywords: ['cache', 'page'],
					},
					{
						id: 'marker-keaqtsok',
						label: i18n.ts.dataSaver,
						keywords: ['datasaver'],
					},
				],
				label: i18n.ts.behavior,
				keywords: ['behavior'],
			},
		],
		label: i18n.ts.general,
		keywords: ['general'],
		icon: 'ti ti-adjustments',
	},
] as const;

export type SearchIndex = typeof searchIndexes;
