name: API report (misskey.js)

on:
  push:
    paths:
      - packages/misskey-js/**
      - .github/workflows/api-misskey-js.yml
  pull_request:
    paths:
      - packages/misskey-js/**
      - .github/workflows/api-misskey-js.yml
jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Use pnpm
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
        with:
          cache: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter misskey-js build

      - name: Check files
        run: ls packages/misskey-js/built

      - name: API report
        run: pnpm --filter misskey-js api-prod

      - name: Show report
        if: always()
        run: cat packages/misskey-js/temp/misskey-js.api.md
