name: Test (production install and build)

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  NODE_ENV: production

jobs:
  production:
    name: Production build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.1
      with:
        submodules: true
    - name: Use pnpm
      uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
      with:
        cache: true
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .github/misskey/test.yml .config/default.yml
    - name: Build
      run: pnpm build
